use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();
    generate_skills_module();
}

/// Generates `skills_embedded.rs` in OUT_DIR with all skill files embedded as
/// string literals via `include_str!`. This removes the runtime dependency on
/// the `.agents/skills/hyperframes/` directory, which is not available in
/// production builds (CWD is `/` on macOS/Linux app bundles).
fn generate_skills_module() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    // CARGO_MANIFEST_DIR = src-tauri/; project root is one level up
    let project_root = Path::new(&manifest_dir)
        .parent()
        .expect("manifest dir must have a parent");
    let skills_dir = project_root.join(".agents/skills/hyperframes");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("skills_embedded.rs");

    let mut entries = Vec::new();
    if skills_dir.exists() {
        walk_skills(&skills_dir, &skills_dir, &mut entries);
    } else {
        println!(
            "cargo:warning=Skills directory not found at {}, skills will be empty",
            skills_dir.display()
        );
    }

    let mut code = String::new();
    code.push_str("/// Auto-generated by build.rs — do not edit.\n");
    code.push_str("/// All files from `.agents/skills/hyperframes/` embedded at compile time.\n");
    code.push_str("pub static FILES: &[(&str, &str)] = &[\n");
    for (rel_path, abs_path) in &entries {
        // Escape backslashes (Windows) so the path is a valid Rust string literal
        let abs_escaped = abs_path.replace('\\', "\\\\");
        code.push_str(&format!(
            "    (\"{}\", include_str!(\"{}\")),\n",
            rel_path, abs_escaped
        ));
    }
    code.push_str("];\n");

    // Re-run build.rs when any skill file changes
    println!("cargo:rerun-if-changed={}", skills_dir.display());

    fs::write(&out_path, code).expect("failed to write skills_embedded.rs");
}

fn walk_skills(base: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    let mut dir_entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read skills dir {}: {}", dir.display(), e))
        .filter_map(|e| e.ok())
        .collect();
    // Sort for deterministic output
    dir_entries.sort_by_key(|e| e.file_name());

    for entry in dir_entries {
        let path = entry.path();
        if path.is_dir() {
            walk_skills(base, &path, entries);
        } else {
            // Only embed text-based skill files (markdown + scripts)
            let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
            if matches!(ext, "md" | "mjs" | "html") {
                let rel = path
                    .strip_prefix(base)
                    .unwrap()
                    .to_str()
                    .unwrap()
                    .replace('\\', "/");
                entries.push((rel, path.to_str().unwrap().to_string()));
            }
        }
    }
}
