export interface VoiceOption {
  id: string;
  name: string;
  chineseName: string;
  description: string;
  /** Language codes supported, e.g. "zh", "en", "fr", ... */
  languages: string[];
  label: string;
}

export const AVAILABLE_VOICES: VoiceOption[] = [
  {
    id: 'Cherry',
    name: 'Cherry',
    chineseName: '芊悦',
    description: '阳光积极、亲切自然小姐姐（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Cherry · 芊悦',
  },
  {
    id: 'Serena',
    name: 'Serena',
    chineseName: '苏瑶',
    description: '温柔小姐姐（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Serena · 苏瑶',
  },
  {
    id: 'Ethan',
    name: 'Ethan',
    chineseName: '晨煦',
    description: '标准普通话，带部分北方口音（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Ethan · 晨煦',
  },
  {
    id: 'Chelsie',
    name: 'Chelsie',
    chineseName: '千雪',
    description: '二次元虚拟女友（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Chelsie · 千雪',
  },
  {
    id: 'Momo',
    name: 'Momo',
    chineseName: '茉兔',
    description: '撒娇搞怪，逗你开心（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Momo · 茉兔',
  },
  {
    id: 'Vivian',
    name: 'Vivian',
    chineseName: '十三',
    description: '拽拽的、可爱的小暴躁（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Vivian · 十三',
  },
  {
    id: 'Moon',
    name: 'Moon',
    chineseName: '月白',
    description: '率性帅气的月白（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Moon · 月白',
  },
  {
    id: 'Maia',
    name: 'Maia',
    chineseName: '四月',
    description: '知性与温柔的碰撞（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Maia · 四月',
  },
  {
    id: 'Kai',
    name: 'Kai',
    chineseName: '凯',
    description: '耳朵的一场SPA（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Kai · 凯',
  },
  {
    id: 'Nofish',
    name: 'Nofish',
    chineseName: '不吃鱼',
    description: '不会翘舌音的设计师（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Nofish · 不吃鱼',
  },
  {
    id: 'Bella',
    name: 'Bella',
    chineseName: '萌宝',
    description: '喝酒不打醉拳的小萝莉（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Bella · 萌宝',
  },
  {
    id: 'Jennifer',
    name: 'Jennifer',
    chineseName: '詹妮弗',
    description: '品牌级、电影质感般美语女声（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Jennifer · 詹妮弗',
  },
  {
    id: 'Ryan',
    name: 'Ryan',
    chineseName: '甜茶',
    description: '节奏拉满，戏感炸裂（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Ryan · 甜茶',
  },
  {
    id: 'Katerina',
    name: 'Katerina',
    chineseName: '卡捷琳娜',
    description: '御姐音色，韵律回味十足（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Katerina · 卡捷琳娜',
  },
  {
    id: 'Aiden',
    name: 'Aiden',
    chineseName: '艾登',
    description: '精通厨艺的美语大男孩（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Aiden · 艾登',
  },
  {
    id: 'Eldric Sage',
    name: 'Eldric Sage',
    chineseName: '沧明子',
    description: '沉稳睿智的老者，沧桑如松却心明如镜（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Eldric Sage · 沧明子',
  },
  {
    id: 'Mia',
    name: 'Mia',
    chineseName: '乖小妹',
    description: '温顺如春水，乖巧如初雪（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Mia · 乖小妹',
  },
  {
    id: 'Mochi',
    name: 'Mochi',
    chineseName: '沙小弥',
    description: '聪明伶俐的小大人，童真未泯却早慧如禅（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Mochi · 沙小弥',
  },
  {
    id: 'Bellona',
    name: 'Bellona',
    chineseName: '燕铮莺',
    description: '字正腔圆间尽显千面人声的江湖（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Bellona · 燕铮莺',
  },
  {
    id: 'Vincent',
    name: 'Vincent',
    chineseName: '田叔',
    description: '一口独特的沙哑烟嗓（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Vincent · 田叔',
  },
  {
    id: 'Bunny',
    name: 'Bunny',
    chineseName: '萌小姬',
    description: '"萌属性"爆棚的小萝莉（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Bunny · 萌小姬',
  },
  {
    id: 'Neil',
    name: 'Neil',
    chineseName: '阿闻',
    description: '最专业的新闻主持人（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Neil · 阿闻',
  },
  {
    id: 'Elias',
    name: 'Elias',
    chineseName: '墨讲师',
    description: '既保持学科严谨性，又通过叙事技巧将复杂知识转化为可消化的认知模块（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Elias · 墨讲师',
  },
  {
    id: 'Arthur',
    name: 'Arthur',
    chineseName: '徐大爷',
    description: '被岁月和旱烟浸泡过的质朴嗓音（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Arthur · 徐大爷',
  },
  {
    id: 'Nini',
    name: 'Nini',
    chineseName: '邻家妹妹',
    description: '糯米糍一样又软又黏的嗓音（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Nini · 邻家妹妹',
  },
  {
    id: 'Seren',
    name: 'Seren',
    chineseName: '小婉',
    description: '温和舒缓的声线，助你更快进入睡眠（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Seren · 小婉',
  },
  {
    id: 'Pip',
    name: 'Pip',
    chineseName: '顽屁小孩',
    description: '调皮捣蛋却充满童真（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Pip · 顽屁小孩',
  },
  {
    id: 'Stella',
    name: 'Stella',
    chineseName: '少女阿月',
    description: '甜到发腻的迷糊少女音（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Stella · 少女阿月',
  },
  {
    id: 'Bodega',
    name: 'Bodega',
    chineseName: '博德加',
    description: '热情的西班牙大叔（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Bodega · 博德加',
  },
  {
    id: 'Sonrisa',
    name: 'Sonrisa',
    chineseName: '索尼莎',
    description: '热情开朗的拉美大姐（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Sonrisa · 索尼莎',
  },
  {
    id: 'Alek',
    name: 'Alek',
    chineseName: '阿列克',
    description: '一开口，是战斗民族的冷，也是毛呢大衣下的暖（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Alek · 阿列克',
  },
  {
    id: 'Dolce',
    name: 'Dolce',
    chineseName: '多尔切',
    description: '慵懒的意大利大叔（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Dolce · 多尔切',
  },
  {
    id: 'Sohee',
    name: 'Sohee',
    chineseName: '素熙',
    description: '温柔开朗，情绪丰富的韩国欧尼（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Sohee · 素熙',
  },
  {
    id: 'Ono Anna',
    name: 'Ono Anna',
    chineseName: '小野杏',
    description: '鬼灵精怪的青梅竹马（女性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Ono Anna · 小野杏',
  },
  {
    id: 'Lenn',
    name: 'Lenn',
    chineseName: '莱恩',
    description: '理性是底色，叛逆藏在细节里（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Lenn · 莱恩',
  },
  {
    id: 'Emilien',
    name: 'Emilien',
    chineseName: '埃米尔安',
    description: '浪漫的法国大哥哥（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Emilien · 埃米尔安',
  },
  {
    id: 'Andre',
    name: 'Andre',
    chineseName: '安德雷',
    description: '声音磁性，自然舒服、沉稳（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Andre · 安德雷',
  },
  {
    id: 'Radio Gol',
    name: 'Radio Gol',
    chineseName: '拉迪奥·戈尔',
    description: '足球诗人（男性）',
    languages: ['zh', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Radio Gol · 拉迪奥·戈尔',
  },
  {
    id: 'Jada',
    name: 'Jada',
    chineseName: '上海-阿珍',
    description: '风风火火的沪上阿姐（女性）',
    languages: ['zh-shanghainese', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Jada · 上海-阿珍',
  },
  {
    id: 'Dylan',
    name: 'Dylan',
    chineseName: '北京-晓东',
    description: '北京胡同里长大的少年（男性）',
    languages: ['zh-beijing', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Dylan · 北京-晓东',
  },
  {
    id: 'Li',
    name: 'Li',
    chineseName: '南京-老李',
    description: '耐心的瑜伽老师（男性）',
    languages: ['zh-nanjing', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Li · 南京-老李',
  },
  {
    id: 'Marcus',
    name: 'Marcus',
    chineseName: '陕西-秦川',
    description: '面宽话短，心实声沉——老陕的味道（男性）',
    languages: ['zh-shaanxi', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Marcus · 陕西-秦川',
  },
  {
    id: 'Roy',
    name: 'Roy',
    chineseName: '闽南-阿杰',
    description: '诙谐直爽、市井活泼的台湾哥仔形象（男性）',
    languages: ['zh-minnan', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Roy · 闽南-阿杰',
  },
  {
    id: 'Peter',
    name: 'Peter',
    chineseName: '天津-李彼得',
    description: '天津相声，专业捧哏（男性）',
    languages: ['zh-tianjin', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Peter · 天津-李彼得',
  },
  {
    id: 'Sunny',
    name: 'Sunny',
    chineseName: '四川-晴儿',
    description: '甜到你心里的川妹子（女性）',
    languages: ['zh-sichuan', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Sunny · 四川-晴儿',
  },
  {
    id: 'Eric',
    name: 'Eric',
    chineseName: '四川-程川',
    description: '一个跳脱市井的四川成都男子（男性）',
    languages: ['zh-sichuan', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Eric · 四川-程川',
  },
  {
    id: 'Rocky',
    name: 'Rocky',
    chineseName: '粤语-阿强',
    description: '幽默风趣的阿强，在线陪聊（男性）',
    languages: ['zh-cantonese', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Rocky · 粤语-阿强',
  },
  {
    id: 'Kiki',
    name: 'Kiki',
    chineseName: '粤语-阿清',
    description: '甜美的港妹闺蜜（女性）',
    languages: ['zh-cantonese', 'en', 'fr', 'de', 'ru', 'it', 'es', 'pt', 'ja', 'ko'],
    label: 'Kiki · 粤语-阿清',
  },
];
