//! Agentic Hyperframes composition generation using rig.
//!
//! This module implements a local AI agent that uses the official Hyperframes
//! skill files (`.agents/skills/hyperframes/`) as dynamic context, with tools
//! for validation, reference loading, and iterative self-correction.
//!
//! Architecture:
//! - System prompt: loaded from SKILL.md (core rules, always present)
//! - Tools:
//!   - `read_reference`: load skill reference docs on demand
//!   - `validate_html`: run composition validation
//! - Agent loop: plan → generate → validate → fix (multi-turn)

use log::info;
use rig_core::client::CompletionClient;
use rig_core::completion::Prompt;
use rig_core::providers;
use serde::Serialize;
use serde_json::json;

use super::timeline::TimelineEntry;
use super::validation::validate_composition;

// Auto-generated by build.rs: embeds all `.agents/skills/hyperframes/` files at compile time.
// This removes the runtime dependency on the filesystem, which is unavailable in production
// builds (CWD is `/` on macOS/Linux app bundles).
mod skills_embedded {
    include!(concat!(env!("OUT_DIR"), "/skills_embedded.rs"));
}

// ─── Skills Loader (compile-time embedded) ───────────────────────────────────

/// Manages skill files embedded at compile time from `.agents/skills/hyperframes/`.
/// All content lives in the binary — no runtime filesystem access needed.
pub struct SkillsContext {
    /// Cached system prompt (SKILL.md + house-style + motion-principles)
    pub system_prompt: String,
}

/// Look up an embedded skill file by its path relative to the skills directory.
fn get_embedded_file(rel_path: &str) -> Option<&'static str> {
    skills_embedded::FILES
        .iter()
        .find(|(p, _)| *p == rel_path)
        .map(|(_, c)| *c)
}

impl SkillsContext {
    /// Create a new SkillsContext by composing the system prompt from embedded files.
    ///
    /// Loads ALL critical reference documents marked "Always read" in SKILL.md.
    /// Total prompt size ~75K chars — well within modern LLM context limits and
    /// essential for high-quality video composition generation.
    pub fn new() -> Result<Self, String> {
        let skill_md = get_embedded_file("SKILL.md")
            .ok_or_else(|| "SKILL.md not found in embedded skills".to_string())?;
        let house_style = get_embedded_file("house-style.md").unwrap_or_default();
        let motion_principles =
            get_embedded_file("references/motion-principles.md").unwrap_or_default();
        // These references are marked "Always read" in SKILL.md — without them
        // the LLM produces generic, low-quality compositions.
        let video_composition =
            get_embedded_file("references/video-composition.md").unwrap_or_default();
        let beat_direction = get_embedded_file("references/beat-direction.md").unwrap_or_default();
        let typography = get_embedded_file("references/typography.md").unwrap_or_default();
        let techniques = get_embedded_file("references/techniques.md").unwrap_or_default();

        let system_prompt = format!(
            "{skill}\n\n---\n\n\
             # House Style (always loaded)\n\n{house}\n\n---\n\n\
             # Motion Principles (always loaded)\n\n{motion}\n\n---\n\n\
             # Video Composition Rules (always loaded)\n\n{video}\n\n---\n\n\
             # Beat Direction (always loaded)\n\n{beat}\n\n---\n\n\
             # Typography (always loaded)\n\n{typo}\n\n---\n\n\
             # Visual Techniques (always loaded)\n\n{tech}",
            skill = skill_md,
            house = house_style,
            motion = motion_principles,
            video = video_composition,
            beat = beat_direction,
            typo = typography,
            tech = techniques,
        );

        Ok(Self { system_prompt })
    }
}

// ─── Agent Builder ──────────────────────────────────────────────────────────

/// Configuration for the agent-based generation.
pub struct AgentConfig {
    pub api_endpoint: String,
    pub api_key: String,
    pub model: String,
}

/// Run the agent-based Hyperframes generation pipeline.
///
/// This is the main entry point for the agent mode. It:
/// 1. Loads skills context (SKILL.md + house-style + motion-principles)
/// 2. Builds a rig agent with tools (read_reference, validate_html)
/// 3. Sends the timeline data as a user prompt
/// 4. Lets the agent iterate (generate → validate → fix) via multi-turn
/// 5. Extracts the final HTML from the agent's response
///
/// `actual_duration_secs` overrides the timeline-computed duration when provided.
/// This should be the ffprobe-measured duration of the merged audio file, ensuring
/// the HTML composition's total duration exactly matches the audio.
pub async fn generate_with_agent(
    entries: &[TimelineEntry],
    config: &AgentConfig,
    on_progress: Option<Box<dyn Fn(&str) + Send + Sync>>,
    user_instructions: Option<&str>,
    actual_duration_secs: Option<f64>,
) -> Result<String, String> {
    let report = |msg: &str| {
        if let Some(ref cb) = on_progress {
            cb(msg);
        }
    };

    report("loading_skills");

    // Load skills context
    let skills = SkillsContext::new()?;
    info!(
        "[Agent] Skills loaded (system prompt: {} chars)",
        skills.system_prompt.len(),
    );

    report("building_agent");

    // Build the OpenAI-compatible client (CompletionsClient for /chat/completions API)
    let client = providers::openai::CompletionsClient::builder()
        .api_key(&config.api_key)
        .base_url(&config.api_endpoint)
        .build()
        .map_err(|e| format!("Failed to build LLM client: {}", e))?;

    // Build the agent — no tools needed for single-turn generation.
    // All references are embedded in the system prompt.
    let agent = client
        .agent(&config.model)
        .preamble(&skills.system_prompt)
        // Temperature 0.4: prioritize format compliance and structural correctness.
        // Visual creativity comes from the rich reference docs in the system prompt,
        // not from high randomness which causes broken GSAP/HTML output.
        .temperature(0.4)
        // Thinking mode enabled: allows the model to reason about complex layouts.
        // The extract_html function strips <think> blocks from the response.
        .additional_params(json!({ "enable_thinking": true }))
        .build();

    // Build the user prompt with timeline data
    // Use actual audio duration if provided (from ffprobe), otherwise fall back to
    // timeline-computed max. The actual duration accounts for loudnorm/resampling drift.
    let timeline_computed_duration: f64 = entries
        .iter()
        .map(|e| e.start_time + e.duration)
        .fold(0.0_f64, f64::max);
    let total_duration = actual_duration_secs.unwrap_or(timeline_computed_duration);

    if let Some(actual) = actual_duration_secs {
        let drift = actual - timeline_computed_duration;
        if drift.abs() > 0.05 {
            info!(
                "[Agent] Using actual audio duration: {:.3}s (timeline computed: {:.3}s, drift: {:.3}s)",
                actual, timeline_computed_duration, drift
            );
        }
    }

    let timeline_json = build_timeline_prompt(entries, total_duration);

    let user_prompt = format!(
        r#"为以下有声书生成 Hyperframes HTML 视觉伴奏视频。

# 你的角色

你是一位动态影像设计师。音频已有完整旁白，你的视频是"视觉伴奏"——营造氛围、传递情绪、强化记忆点。观众听着音频，看着你的画面感受内容的力量。

# 内容呈现

从每一段内容中提炼 1-3 个关键短语（每个 ≤ 15 字）作为视觉亮点——金句、核心概念、人名地名。
这些短语是画面中的"锚点"，用 80px+ 大字号、动感入场（slam / slide / scale）让观众一眼抓住。

# 视觉丰富度

每个场景 6-10 个视觉元素，分层构建：
- **文字层**：关键词/短句，80px+，动感入场
- **几何层**：旋转圆环、脉动多边形、流动线条网格
- **背景层**：渐变流动、radial glow 呼吸、粒子漂浮
- **结构层**：动态 accent lines、扩展边框、reveal 效果
- **数据层**（可选）：progress bar、counter 计数、node 连接线

让画面持续运动——装饰元素 2-5s 一个循环，主元素入场 0.5-1.2s，元素分批 stagger 入场形成节奏。
"看一眼就能感受到生命力"是你的最低标准。

# 场景与节奏

- 每 10-20 秒一个场景，根据内容和情绪变化划分
- 每个场景有独特的视觉个性（不同主体几何、不同动画方向），但调色板统一
- 场景间用 crossfade / wipe / blur-through 平滑过渡
- 最后一个场景淡出收束，其余场景只做入场动画（退场由过渡处理）
- 参考 beat-direction.md 规划快拍与慢拍交替
- 同一场景内至少 3 种不同的 ease

时间轴数据（JSON）：
{timeline}

总时长：{duration:.2} 秒，条目数：{count}
{user_section}

# 视觉设计

按照 house-style.md 和 video-composition.md 的规则：
1. 选择匹配内容情绪的调色板，声明 bg/fg/accent
2. 选择有特色的字体（参考 typography.md）
3. 场景主视觉运用 techniques.md 中的技巧（SVG drawing、CSS 3D、kinetic type 等）

# 时间轴同步

每个条目的 start 和 duration 精确对应音频时间：
- clip 的 data-start = 条目 start（秒）
- clip 的 data-duration = 条目 duration（秒）
- 条目间的间隔保留
- 整个作品 t=0 开始，t={duration:.2}s 结束
- 多个条目可共享一个视觉场景，但每条仍需对应的 clip 元素

# 渲染引擎技术要求

这些是 Hyperframes 渲染器的硬性要求，违反任何一条都会导致渲染失败：

1. 根元素：data-composition-id="ai-generated"，data-width="1920"，data-height="1080"，data-duration="{duration:.2}"
2. GSAP timeline 使用 paused: true
3. 同步注册 window.__timelines['ai-generated'] = tl;（在 </body> 前的 <script> 中直接执行）
4. 注册方式必须是同步代码——setTimeout、async、Promise 回调中的注册会被渲染器忽略
5. 实现 window.__hf = {{ duration: {duration:.2}, seek: function(t) {{ Object.values(window.__timelines).forEach(function(tl) {{ tl.seek(t) }}) }} }}
6. GSAP CDN: <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
7. 渲染器逐帧截图，所以所有动画必须是确定性的——使用 seed、公式、固定时间线，确保同一帧每次渲染结果完全一致
8. 关键词字号 80px+，数字用 font-variant-numeric: tabular-nums
9. gsap.from() 做入场动画，gsap.to() 仅用于最后场景的退出动画
10. 每个入场 tween 起始时间偏移 0.1-0.3s

# 输出

输出完整 HTML 文档：<!DOCTYPE html> 开头，</html> 结尾，中间不加任何解释文字或代码围栏。"#,
        user_section = match user_instructions {
            Some(instructions) if !instructions.is_empty() =>
                format!("\n用户额外要求（请务必遵循）：\n{}\n", instructions),
            _ => String::new(),
        },
        timeline = timeline_json,
        duration = total_duration,
        count = entries.len(),
    );

    report("agent_generating");

    // Run the agent with single turn — force direct HTML generation.
    // All necessary references (beat-direction, techniques) are already in the system prompt.
    // Tool calls would waste turns on read_reference instead of generating.
    // Retry up to 2 times on extraction failure (LLM may return malformed output).
    let max_attempts = 2;
    let mut last_error: Option<String> = None;
    let mut html = String::new();

    for attempt in 1..=max_attempts {
        let start = std::time::Instant::now();
        info!(
            "[Agent] Sending prompt to LLM (model: {}, attempt {}/{})...",
            config.model, attempt, max_attempts
        );

        let response = agent
            .prompt(&user_prompt)
            .max_turns(1)
            .await
            .map_err(|e| format!("Agent execution failed: {}", e))?;
        info!("[Agent] LLM response received in {:?}", start.elapsed());

        report("extracting_html");

        // Log the response for debugging — use char boundary safe truncation
        info!("[Agent] Response length: {} chars", response.len());
        let preview_end = response
            .char_indices()
            .take_while(|(i, _)| *i < 200)
            .last()
            .map(|(i, c)| i + c.len_utf8())
            .unwrap_or(0);
        info!("[Agent] Response preview: {}", &response[..preview_end]);

        // Extract HTML from the agent's final response
        match extract_html(&response) {
            Ok(extracted) => {
                html = extracted;
                last_error = None;
                break;
            }
            Err(e) => {
                info!(
                    "[Agent] HTML extraction failed on attempt {}: {}",
                    attempt, e
                );
                last_error = Some(e);
                if attempt < max_attempts {
                    info!("[Agent] Retrying LLM generation...");
                    report("retrying");
                }
            }
        }
    }

    if let Some(err) = last_error {
        return Err(err);
    }

    // Post-process: fix common issues as a safety net
    let html = fix_css_font_variables(&html);
    let html = sanitize_unsupported_fonts(&html);
    let html = ensure_hyperframes_interfaces(&html, total_duration);
    let html = ensure_root_duration(&html, total_duration);
    let html = ensure_clip_timing(&html, entries);
    // Final guard: no clip may extend beyond the audio duration.
    let html = clamp_overflow_clips(&html, total_duration);

    // Final validation
    match validate_composition(&html) {
        Ok(()) => {
            info!("[Agent] Generation complete, validation passed");
            report("agent_done");
            Ok(html)
        }
        Err(errors) => {
            info!(
                "[Agent] Generation complete with {} validation warnings",
                errors.len()
            );
            report("agent_done_with_warnings");
            Ok(html)
        }
    }
}

/// Build the timeline data as a JSON string for the user prompt.
///
/// For audiobook visual accompaniment, we truncate long text entries and provide
/// only the first ~40 chars as context hint. The full text is NOT meant to be
/// displayed verbatim in the video — it's only provided so the LLM can understand
/// the content theme and mood for visual design.
fn build_timeline_prompt(entries: &[TimelineEntry], total_duration: f64) -> String {
    #[derive(Serialize)]
    struct TimelineData {
        total_duration: f64,
        entries: Vec<EntryData>,
    }

    #[derive(Serialize)]
    struct EntryData {
        /// Truncated text hint — for understanding content theme only, NOT for display
        content_hint: String,
        start: f64,
        duration: f64,
        character: String,
        section: String,
    }

    let data = TimelineData {
        total_duration,
        entries: entries
            .iter()
            .map(|e| {
                // Truncate text to ~60 chars to discourage verbatim display.
                // Preserve enough context for the LLM to understand the theme/mood.
                let hint = if e.text.chars().count() > 60 {
                    let truncated: String = e.text.chars().take(57).collect();
                    format!("{}...", truncated)
                } else {
                    e.text.clone()
                };
                EntryData {
                    content_hint: hint,
                    start: e.start_time,
                    duration: e.duration,
                    character: e.character_name.clone().unwrap_or_default(),
                    section: e.section_title.clone().unwrap_or_default(),
                }
            })
            .collect(),
    };

    serde_json::to_string_pretty(&data).unwrap_or_default()
}

/// Fix CSS font variables by replacing var(--font-*) with actual font names.
/// This is necessary because hyperframes cannot map CSS variables to fonts.
/// Uses non-banned fonts from the typography reference for better visual quality.
fn fix_css_font_variables(html: &str) -> String {
    let mut result = html.to_string();

    // Replace common font variable patterns with hyperframes-supported fonts.
    // Avoid banned fonts (Inter, Roboto, etc.) — use distinctive alternatives.
    // IMPORTANT: Use actual font display names (e.g., "DM Sans" not "dm-sans")
    // because hyperframes maps CSS font-family names to its internal IDs.
    // Pattern 1: Standard --font-* naming
    result = result
        .replace("var(--font-body)", "'DM Sans', sans-serif")
        .replace("var(--font-heading)", "'Space Grotesk', sans-serif")
        .replace("var(--font-mono)", "'JetBrains Mono', monospace")
        .replace("var(--font-main)", "'DM Sans', sans-serif")
        .replace("var(--font-display)", "'Space Grotesk', sans-serif")
        .replace("var(--font-serif)", "'Libre Baskerville', serif")
        .replace("var(--font-sans)", "'DM Sans', sans-serif");

    // Pattern 2: Short naming (--mono, --sans, --serif)
    result = result
        .replace("var(--mono)", "'JetBrains Mono', monospace")
        .replace("var(--sans)", "'DM Sans', sans-serif")
        .replace("var(--serif)", "'Libre Baskerville', serif")
        .replace("var(--body)", "'DM Sans', sans-serif")
        .replace("var(--heading)", "'Space Grotesk', sans-serif");

    // Pattern 3: Suffix naming (--body-font, --heading-font)
    result = result
        .replace("var(--body-font)", "'DM Sans', sans-serif")
        .replace("var(--heading-font)", "'Space Grotesk', sans-serif")
        .replace("var(--mono-font)", "'JetBrains Mono', monospace");

    // Pattern 4: Primary/secondary naming
    result = result
        .replace("var(--font-primary)", "'DM Sans', sans-serif")
        .replace("var(--font-secondary)", "'Space Grotesk', sans-serif");

    // Fix kebab-case internal IDs that the LLM or our own code might have output
    // These are hyperframes internal names, not valid CSS font names.
    result = result
        .replace("'jetbrains-mono'", "'JetBrains Mono'")
        .replace("\"jetbrains-mono\"", "\"JetBrains Mono\"")
        .replace("'dm-sans'", "'DM Sans'")
        .replace("\"dm-sans\"", "\"DM Sans\"")
        .replace("'space-grotesk'", "'Space Grotesk'")
        .replace("\"space-grotesk\"", "\"Space Grotesk\"")
        .replace("'libre-baskerville'", "'Libre Baskerville'")
        .replace("\"libre-baskerville\"", "\"Libre Baskerville\"")
        .replace("'archivo-black'", "'Archivo Black'")
        .replace("\"archivo-black\"", "\"Archivo Black\"")
        .replace("'comic-neue'", "'Comic Neue'")
        .replace("\"comic-neue\"", "\"Comic Neue\"")
        .replace("'playfair-display'", "'Playfair Display'")
        .replace("\"playfair-display\"", "\"Playfair Display\"")
        .replace("'fira-code'", "'Fira Code'")
        .replace("\"fira-code\"", "\"Fira Code\"");

    result
}

/// Strip all specific font names from font-family declarations at generation time.
///
/// Hyperframes compiler treats ANY unmapped font name as a fatal error (exit 1),
/// regardless of whether a generic fallback is present. There's no CLI flag to
/// suppress this. So we must remove all specific font names before rendering.
///
/// We preserve the intended category (sans/serif/mono) by detecting keywords in
/// the original value and mapping to the correct generic family.
fn sanitize_unsupported_fonts(html: &str) -> String {
    sanitize_fonts_for_retry(html)
}

/// Strip all specific font names from font-family declarations, keeping only
/// generic CSS families (sans-serif, serif, monospace). Called by the render
/// retry path when the first attempt fails due to unmapped fonts.
pub fn sanitize_fonts_for_retry(html: &str) -> String {
    let mut result = html.to_string();

    // Pattern 1: Explicit font-family declarations
    let font_family_re = regex::Regex::new(r#"font-family\s*:\s*([^;}"]+)"#).unwrap();

    let matches: Vec<(usize, usize, String)> = font_family_re
        .find_iter(&result)
        .map(|m| (m.start(), m.end(), m.as_str().to_string()))
        .collect();

    for (start, end, matched) in matches.into_iter().rev() {
        let colon_pos = matched.find(':').unwrap_or(0);
        let value_part = matched[colon_pos + 1..].trim().to_lowercase();

        if is_all_generic(&value_part) {
            continue;
        }

        let replacement = infer_generic_family(&value_part);
        let new_declaration = format!("font-family: {}", replacement);
        result.replace_range(start..end, &new_declaration);
    }

    // Pattern 2: CSS `font` shorthand — the font family comes after the size/line-height.
    // e.g., `font: bold 16px/1.5 "Noto Serif CJK SC", STSong, serif;`
    // We replace the entire font shorthand's family portion with just the generic.
    let font_shorthand_re = regex::Regex::new(r#"(?i)\bfont\s*:\s*([^;}"]*)"#).unwrap();
    let size_re =
        regex::Regex::new(r#"[\d.]+(?:px|em|rem|pt|vw|vh|%|ex|ch)(?:\s*/\s*[\d.]+)?"#).unwrap();

    let matches: Vec<(usize, usize, String)> = font_shorthand_re
        .find_iter(&result)
        .map(|m| (m.start(), m.end(), m.as_str().to_string()))
        .collect();

    for (start, end, matched) in matches.into_iter().rev() {
        // Skip if this is actually font-family, font-size, font-weight, etc.
        let prop_name = matched
            .split(':')
            .next()
            .unwrap_or("")
            .trim()
            .to_lowercase();
        if prop_name != "font" {
            continue;
        }

        let colon_pos = matched.find(':').unwrap_or(0);
        let value_part = matched[colon_pos + 1..].trim();

        // The font shorthand format: [style] [variant] [weight] [stretch] size[/line-height] family
        // We need to find where the family part starts (after size/line-height).
        // Strategy: find all quoted strings and known font names, replace them with generic.
        let lower_value = value_part.to_lowercase();

        // If it contains a specific font name (quoted or known CJK fonts), sanitize
        let has_specific_font = value_part.contains('"')
            || value_part.contains('\'')
            || lower_value.contains("noto")
            || lower_value.contains("song")
            || lower_value.contains("hei")
            || lower_value.contains("kai")
            || lower_value.contains("ming")
            || lower_value.contains("gothic");

        if !has_specific_font {
            continue;
        }

        // Find the family portion: everything after the last numeric value (size/line-height)
        // Look for pattern like "16px" or "1.5em" or "16px/1.5"
        if let Some(size_match) = size_re.find(value_part) {
            let family_start_in_value = size_match.end();
            let family_part = value_part[family_start_in_value..].trim();

            if !is_all_generic(&family_part.to_lowercase()) {
                let replacement = infer_generic_family(&family_part.to_lowercase());
                let new_value = format!(
                    "font: {} {}",
                    value_part[..family_start_in_value].trim(),
                    replacement
                );
                result.replace_range(start..end, &new_value);
            }
        }
    }

    // Pattern 3: Remove @font-face blocks entirely — they reference external fonts
    // that hyperframes can't resolve and will error on.
    let fontface_re = regex::Regex::new(r#"(?is)@font-face\s*\{[^}]*\}"#).unwrap();
    result = fontface_re.replace_all(&result, "").to_string();

    result
}

/// Check if a font value string contains only generic CSS families.
fn is_all_generic(value: &str) -> bool {
    value.split(',').all(|f| {
        let f = f.trim().trim_matches('\'').trim_matches('"').trim();
        matches!(
            f,
            "sans-serif"
                | "serif"
                | "monospace"
                | "cursive"
                | "fantasy"
                | "inherit"
                | "initial"
                | "unset"
                | ""
        )
    })
}

/// Infer the best generic fallback from a font declaration's value.
fn infer_generic_family(value: &str) -> &'static str {
    if value.contains("mono") || value.contains("code") || value.contains("courier") {
        "monospace"
    } else if (value.contains("serif")
        || value.contains("song")
        || value.contains("ming")
        || value.contains("baskerville")
        || value.contains("georgia")
        || value.contains("times"))
        && !value.contains("sans")
    {
        "serif"
    } else {
        "sans-serif"
    }
}

/// Ensure required Hyperframes interfaces exist (window.__hf and window.__timelines).
/// This is a safety net to fix LLM omissions and ensure hyperframes render compatibility.
///
/// The render engine requires `window.__timelines['ai-generated']` to be registered
/// SYNCHRONOUSLY at page load. If the LLM's GSAP code throws an error, the registration
/// never happens and render fails with "Composition has zero duration".
///
/// Strategy: ALWAYS inject a fallback script at the very end of </body> that checks
/// whether the timeline was registered, and if not, creates a minimal empty one.
/// This way even if the LLM's code crashes, the render engine won't hang.
fn ensure_hyperframes_interfaces(html: &str, duration: f64) -> String {
    let mut result = html.to_string();

    // Always inject a robust fallback script that:
    // 1. Ensures window.__timelines exists and has 'ai-generated' key
    // 2. FORCES window.__hf.duration to the correct value (LLM often gets this wrong)
    // 3. Ensures window.__hf.seek exists
    // This runs AFTER the LLM's script. The duration is ALWAYS overwritten because
    // LLMs frequently set incorrect duration values causing videos that are too long.
    let fallback_script = format!(
        r#"<script>
// === Hyperframes safety-net (always injected) ===
(function() {{
  window.__timelines = window.__timelines || {{}};
  if (!window.__timelines['ai-generated']) {{
    // LLM script failed to register timeline — create minimal fallback
    if (typeof gsap !== 'undefined') {{
      window.__timelines['ai-generated'] = gsap.timeline({{ paused: true }});
    }} else {{
      window.__timelines['ai-generated'] = {{ seek: function() {{}}, duration: function() {{ return {dur:.2}; }} }};
    }}
  }}
  // ALWAYS force correct duration — LLM frequently outputs wrong values
  // causing videos that render far longer than the audio (trailing black frames).
  window.__hf = window.__hf || {{}};
  window.__hf.duration = {dur:.2};
  if (!window.__hf.seek) {{
    window.__hf.seek = function(time) {{
      if (window.__timelines) {{
        Object.values(window.__timelines).forEach(function(tl) {{
          if (tl && typeof tl.seek === 'function') tl.seek(time);
        }});
      }}
    }};
  }}
}})();
</script>"#,
        dur = duration,
    );

    // Inject before </body> if it exists, otherwise before </html>, otherwise append
    if let Some(pos) = result.rfind("</body>") {
        result.insert_str(pos, &fallback_script);
    } else if let Some(pos) = result.rfind("</html>") {
        result.insert_str(pos, &fallback_script);
    } else {
        result.push_str(&fallback_script);
    }

    info!(
        "[Agent] Post-processed: injected safety-net interfaces (duration={:.2})",
        duration
    );

    result
}

/// Find the byte range (tag_start..=tag_end) of the opening tag that carries
/// `data-composition-id` as a REAL HTML attribute — not a CSS selector occurrence
/// like `[data-composition-id="x"]` inside a `<style>` block.
///
/// Returns None if no genuine element attribute is found.
fn find_composition_tag_range(html: &str) -> Option<(usize, usize)> {
    let needle = "data-composition-id";
    let mut search_from = 0;

    while let Some(rel) = html[search_from..].find(needle) {
        let pos = search_from + rel;
        search_from = pos + needle.len();

        // The char immediately before must be ASCII whitespace for an HTML attribute.
        // CSS selectors use `[data-composition-id` (preceded by `[`), so this rejects them.
        let prev_char = html[..pos].chars().next_back();
        if !matches!(prev_char, Some(c) if c.is_whitespace()) {
            continue;
        }

        // Walk back to the enclosing `<` and confirm it opens a real element
        // (next char after `<` is an ASCII letter — a tag name).
        let Some(tag_start) = html[..pos].rfind('<') else {
            continue;
        };
        let after_lt = html[tag_start + 1..].chars().next();
        if !matches!(after_lt, Some(c) if c.is_ascii_alphabetic()) {
            continue;
        }

        // Ensure the attribute is within THIS tag (no `>` between `<` and the attribute)
        if html[tag_start..pos].contains('>') {
            continue;
        }

        // Find the closing `>` of this tag
        let Some(end_rel) = html[tag_start..].find('>') else {
            continue;
        };
        let tag_end = tag_start + end_rel;
        return Some((tag_start, tag_end));
    }

    None
}

/// Set (or replace) `data-duration` to `duration` within the tag at `tag_start..=tag_end`.
/// Returns the modified full HTML and whether a change was made.
/// Only replaces when the existing value differs from `duration` by more than 0.1s.
fn set_data_duration_in_tag(
    html: &str,
    tag_start: usize,
    tag_end: usize,
    duration: f64,
) -> (String, bool) {
    let tag_content = &html[tag_start..=tag_end];

    if let Some(attr_pos) = tag_content.find("data-duration=") {
        let after_eq = attr_pos + "data-duration=".len();
        if let Some(quote) = tag_content[after_eq..].chars().next() {
            if quote == '"' || quote == '\'' {
                let value_start = after_eq + 1;
                if let Some(value_end_rel) = tag_content[value_start..].find(quote) {
                    let current_val = &tag_content[value_start..value_start + value_end_rel];
                    // Always replace unless already correct within tight tolerance.
                    let needs_fix = current_val
                        .parse::<f64>()
                        .map(|v| (v - duration).abs() > 0.1)
                        .unwrap_or(true);
                    if !needs_fix {
                        return (html.to_string(), false);
                    }
                    let new_attr = format!("data-duration=\"{:.3}\"", duration);
                    let attr_end = value_start + value_end_rel + 1; // past closing quote
                    let new_tag = format!(
                        "{}{}{}",
                        &tag_content[..attr_pos],
                        new_attr,
                        &tag_content[attr_end..]
                    );
                    let mut result = html.to_string();
                    result.replace_range(tag_start..=tag_end, &new_tag);
                    return (result, true);
                }
            }
        }
        // Malformed attribute — leave unchanged
        (html.to_string(), false)
    } else {
        // No data-duration: insert it just before the closing `>`
        let addition = format!(" data-duration=\"{:.3}\"", duration);
        let mut result = html.to_string();
        result.insert_str(tag_end, &addition);
        (result, true)
    }
}

/// Ensure the root composition element has the correct `data-duration` attribute.
/// This is critical because hyperframes uses this value to determine how many frames
/// to render. If the duration is wrong, the video will be too long (trailing blank
/// frames) or too short (cut off).
///
/// Root cause handling:
/// - Finds `data-composition-id` only as a real HTML attribute (ignores CSS selectors
///   in `<style>` blocks, which previously caused the wrong tag to be matched).
/// - Forces `data-duration` on the composition element to the ffprobe-measured audio duration.
/// - Also fixes `data-duration` on a separate `<html>` element if present.
fn ensure_root_duration(html: &str, duration: f64) -> String {
    let mut result = html.to_string();
    let mut corrections = 0;
    let mut comp_is_on_html_tag = false;

    // Fix data-duration on the composition element (real attribute, not CSS).
    if let Some((tag_start, tag_end)) = find_composition_tag_range(&result) {
        // Determine if the composition attribute lives on the <html> tag itself.
        let tag_name_end = result[tag_start + 1..]
            .find(|c: char| c.is_whitespace() || c == '>')
            .map(|i| i + tag_start + 1)
            .unwrap_or(tag_start + 1);
        let tag_name = result[tag_start + 1..tag_name_end].to_string();
        comp_is_on_html_tag = tag_name.eq_ignore_ascii_case("html");

        let (new_html, changed) = set_data_duration_in_tag(&result, tag_start, tag_end, duration);
        if changed {
            result = new_html;
            corrections += 1;
            info!(
                "[Agent] Set composition data-duration to {:.3} on <{}>",
                duration, tag_name
            );
        }
    } else {
        info!("[Agent] No composition element with data-composition-id found");
    }

    // Also fix data-duration on a separate <html> element if present.
    if !comp_is_on_html_tag {
        if let Some(html_start) = result.find("<html") {
            if let Some(html_end_rel) = result[html_start..].find('>') {
                let html_end = html_start + html_end_rel;
                // Only touch <html> if it already declares data-duration (don't add one there).
                if result[html_start..=html_end].contains("data-duration=") {
                    let (new_html, changed) =
                        set_data_duration_in_tag(&result, html_start, html_end, duration);
                    if changed {
                        result = new_html;
                        corrections += 1;
                        info!("[Agent] Fixed <html> data-duration to {:.3}", duration);
                    }
                }
            }
        }
    }

    if corrections == 0 {
        info!(
            "[Agent] data-duration already correct ({:.3}), no changes needed",
            duration
        );
    }

    result
}

/// Ensure clip elements have correct data-start and data-duration matching the timeline.
///
/// LLMs often generate clips with slightly wrong timing values. This function
/// parses the HTML for clip elements and corrects their timing attributes to match
/// the authoritative timeline entries.
///
/// Matching strategy:
/// - If a clip already has a data-start value, match it to the closest timeline entry
///   (by start time proximity). This avoids breaking the LLM's intended structure
///   when clips are not in document order.
/// - Only clips with class="clip" and existing data-start are corrected.
/// - Unmatched clips (decorative, scene containers) are left unchanged.
///
/// This is the final safety net for audio-video synchronization: even if the LLM
/// outputs slightly incorrect timing, the post-processed HTML will have frame-accurate timing.
fn ensure_clip_timing(html: &str, entries: &[TimelineEntry]) -> String {
    if entries.is_empty() {
        return html.to_string();
    }

    let mut result = html.to_string();
    let mut corrections = 0;

    // Find all clip elements with class="clip" (the hyperframes standard).
    let mut clip_positions: Vec<(usize, usize)> = Vec::new(); // (tag_start, tag_end)
    let lower = result.to_ascii_lowercase();
    let mut search_from = 0;

    while let Some(class_pos) = lower[search_from..].find("class=\"clip") {
        let abs_pos = search_from + class_pos;
        // Find the opening < of this tag
        if let Some(tag_start) = result[..abs_pos].rfind('<') {
            // Find the end of the tag (> or />)
            if let Some(tag_end_rel) = result[tag_start..].find('>') {
                let tag_end = tag_start + tag_end_rel;
                clip_positions.push((tag_start, tag_end));
            }
        }
        search_from = abs_pos + 1;
    }

    // Extract current data-start values from clips for proximity matching.
    // Build (clip_index, parsed_start_time) pairs for clips that have data-start.
    let mut clips_with_start: Vec<(usize, f64)> = Vec::new();
    for (i, &(tag_start, tag_end)) in clip_positions.iter().enumerate() {
        let tag_content = &result[tag_start..=tag_end];
        if let Some(start_val) = extract_attr_value(tag_content, "data-start") {
            if let Ok(t) = start_val.parse::<f64>() {
                clips_with_start.push((i, t));
            }
        }
    }

    // Match clips to timeline entries by proximity of their data-start values.
    // Each entry is matched to the clip whose existing data-start is closest.
    // Track which entries have been matched to avoid double-assignment.
    let mut entry_matched: Vec<bool> = vec![false; entries.len()];
    // (clip_index, entry_index) pairs for correction
    let mut match_pairs: Vec<(usize, usize)> = Vec::new();

    for &(clip_idx, clip_start) in &clips_with_start {
        let mut best_entry_idx: Option<usize> = None;
        let mut best_distance = f64::MAX;

        for (entry_idx, entry) in entries.iter().enumerate() {
            if entry_matched[entry_idx] {
                continue;
            }
            let distance = (clip_start - entry.start_time).abs();
            if distance < best_distance {
                best_distance = distance;
                best_entry_idx = Some(entry_idx);
            }
        }

        if let Some(entry_idx) = best_entry_idx {
            // Only match if the clip's start time is reasonably close (within 5 seconds).
            // If it's too far off, the clip might be a decorative/scene element, not a text clip.
            if best_distance < 5.0 {
                entry_matched[entry_idx] = true;
                match_pairs.push((clip_idx, entry_idx));
            }
        }
    }

    // If proximity matching found fewer matches than expected, fall back to order-based
    // matching for unmatched entries. This handles cases where LLM didn't set data-start
    // correctly at all.
    if match_pairs.len() < entries.len() && clip_positions.len() >= entries.len() {
        let matched_clips: std::collections::HashSet<usize> =
            match_pairs.iter().map(|(c, _)| *c).collect();
        let unmatched_clips: Vec<usize> = (0..clip_positions.len())
            .filter(|i| !matched_clips.contains(i))
            .collect();
        let unmatched_entries: Vec<usize> =
            (0..entries.len()).filter(|i| !entry_matched[*i]).collect();

        // Match remaining clips to remaining entries by order
        let fallback_count = unmatched_entries.len().min(unmatched_clips.len());
        for i in 0..fallback_count {
            match_pairs.push((unmatched_clips[i], unmatched_entries[i]));
        }
    }

    // Sort by clip_index descending so we can replace without invalidating positions
    match_pairs.sort_by_key(|b| std::cmp::Reverse(b.0));

    // Apply corrections
    for (clip_idx, entry_idx) in &match_pairs {
        let (tag_start, tag_end) = clip_positions[*clip_idx];
        let entry = &entries[*entry_idx];
        let tag_content = &result[tag_start..=tag_end];

        let mut new_tag = tag_content.to_string();

        // Replace or add data-start
        new_tag = replace_or_add_attr(&new_tag, "data-start", &format!("{:.3}", entry.start_time));
        // Replace or add data-duration
        new_tag = replace_or_add_attr(&new_tag, "data-duration", &format!("{:.3}", entry.duration));

        if new_tag != tag_content {
            corrections += 1;
            result.replace_range(tag_start..=tag_end, &new_tag);
        }
    }

    if corrections > 0 {
        info!(
            "[Agent] Post-processed: corrected timing on {}/{} clip elements (proximity-matched)",
            corrections,
            clip_positions.len()
        );
    }

    result
}

/// Clamp any clip whose `data-start + data-duration` extends beyond `total_duration`.
///
/// This is a final guard against the "video longer than audio" problem: even after
/// fixing the root composition duration, a stray decorative/scene clip with an
/// oversized `data-duration` could extend the rendered timeline past the audio.
/// We clamp every clip so the maximum extent never exceeds the audio duration.
fn clamp_overflow_clips(html: &str, total_duration: f64) -> String {
    if total_duration <= 0.0 {
        return html.to_string();
    }

    let mut result = html.to_string();
    let lower = result.to_ascii_lowercase();

    // Collect all clip tag ranges
    let mut clip_positions: Vec<(usize, usize)> = Vec::new();
    let mut search_from = 0;
    while let Some(rel) = lower[search_from..].find("class=\"clip") {
        let abs_pos = search_from + rel;
        if let Some(tag_start) = result[..abs_pos].rfind('<') {
            if let Some(end_rel) = result[tag_start..].find('>') {
                clip_positions.push((tag_start, tag_start + end_rel));
            }
        }
        search_from = abs_pos + 1;
    }

    // Process from last to first to keep byte positions valid after edits.
    let mut clamped = 0;
    for &(tag_start, tag_end) in clip_positions.iter().rev() {
        let tag_content = result[tag_start..=tag_end].to_string();

        let start =
            extract_attr_value(&tag_content, "data-start").and_then(|v| v.parse::<f64>().ok());
        let dur =
            extract_attr_value(&tag_content, "data-duration").and_then(|v| v.parse::<f64>().ok());

        if let (Some(start), Some(dur)) = (start, dur) {
            // Allow a small epsilon for float rounding.
            if start + dur > total_duration + 0.05 {
                let clamped_dur = (total_duration - start).max(0.0);
                let new_tag = replace_or_add_attr(
                    &tag_content,
                    "data-duration",
                    &format!("{:.3}", clamped_dur),
                );
                if new_tag != tag_content {
                    result.replace_range(tag_start..=tag_end, &new_tag);
                    clamped += 1;
                }
            }
        }
    }

    if clamped > 0 {
        info!(
            "[Agent] Clamped {} clip(s) that extended beyond total duration {:.3}s",
            clamped, total_duration
        );
    }

    result
}

/// Extract the value of an attribute from an HTML tag string.
fn extract_attr_value<'a>(tag: &'a str, attr_name: &str) -> Option<&'a str> {
    let search = format!("{}=", attr_name);
    let attr_pos = tag.find(&search)?;
    let after_eq = attr_pos + search.len();
    let rest = &tag[after_eq..];
    let quote = rest.chars().next()?;
    if quote != '"' && quote != '\'' {
        return None;
    }
    let value_start = after_eq + 1;
    let value_end_rel = tag[value_start..].find(quote)?;
    Some(&tag[value_start..value_start + value_end_rel])
}

/// Replace an attribute's value in an HTML tag string, or add it if missing.
fn replace_or_add_attr(tag: &str, attr_name: &str, new_value: &str) -> String {
    let search = format!("{}=", attr_name);
    if let Some(attr_pos) = tag.find(&search) {
        // Attribute exists — find and replace its value
        let after_eq = attr_pos + search.len();
        let rest = &tag[after_eq..];
        let quote_char = rest.chars().next();
        if let Some(quote) = quote_char {
            if quote == '"' || quote == '\'' {
                let value_start = after_eq + 1;
                if let Some(value_end_rel) = tag[value_start..].find(quote) {
                    let value_end = value_start + value_end_rel;
                    return format!(
                        "{}{}=\"{}\"{}",
                        &tag[..attr_pos],
                        attr_name,
                        new_value,
                        &tag[value_end + 1..]
                    );
                }
            }
        }
        // Couldn't parse quotes, return unchanged
        tag.to_string()
    } else {
        // Attribute doesn't exist — add before the closing >
        if let Some(close_pos) = tag.rfind('>') {
            format!(
                "{} {}=\"{}\"{}",
                &tag[..close_pos],
                attr_name,
                new_value,
                &tag[close_pos..]
            )
        } else {
            tag.to_string()
        }
    }
}

/// Extract the HTML content from the LLM response.
///
/// The LLM is instructed to output raw HTML, but may still wrap it in
/// explanations or code fences. This function handles multiple cases:
/// 1. Raw HTML (starts with <!DOCTYPE or <html)
/// 2. HTML wrapped in ```html ... ``` code fences
/// 3. HTML embedded in explanatory text
/// 4. HTML with leading/trailing whitespace or text
fn extract_html(response: &str) -> Result<String, String> {
    // Strip thinking blocks (e.g., <think>...</think>) that models emit in thinking mode.
    // These appear before the actual HTML content and would otherwise confuse extraction.
    let cleaned = strip_thinking_blocks(response);
    let trimmed = cleaned.trim();

    // Fast path: already raw HTML
    if let Some(html) = try_extract_raw_html(trimmed) {
        return Ok(html);
    }

    // Try to strip markdown code fences: ```html ... ``` or ``` ... ```
    if let Some(html) = try_extract_from_code_fences(trimmed) {
        return Ok(html);
    }

    // Last resort: search for HTML patterns anywhere in the text
    if let Some(html) = try_extract_embedded_html(trimmed) {
        return Ok(html);
    }

    // Generate a better error message with actual preview
    let preview: String = trimmed.chars().take(300).collect();
    Err(format!(
        "LLM response does not contain valid HTML.\n\nResponse preview (first 300 chars):\n{}\n\n\
         Hint: Ensure the model outputs raw HTML starting with <!DOCTYPE html> or <html>.",
        preview
    ))
}

/// Strip `<think>...</think>` blocks from the response.
/// Models with thinking mode enabled may prepend reasoning in these tags.
fn strip_thinking_blocks(text: &str) -> String {
    let mut result = text.to_string();
    // Repeatedly remove <think>...</think> blocks (case-insensitive, possibly multiline)
    loop {
        let lower = result.to_ascii_lowercase();
        let Some(start) = lower.find("<think>") else {
            break;
        };
        let end_tag = "</think>";
        if let Some(end_pos) = lower[start..].find(end_tag) {
            let remove_end = start + end_pos + end_tag.len();
            result = format!("{}{}", &result[..start], &result[remove_end..]);
        } else {
            // Opening <think> without closing tag — remove from <think> to end of text
            // since the rest is likely all thinking content
            result = result[..start].to_string();
            break;
        }
    }
    result
}

/// Try to extract HTML that starts at the beginning of the text.
fn try_extract_raw_html(text: &str) -> Option<String> {
    let lower = text.to_ascii_lowercase();
    if lower.starts_with("<!doctype") || lower.starts_with("<html") {
        Some(text.trim().to_string())
    } else {
        None
    }
}

/// Try to extract HTML from markdown code fences.
/// Handles: ```html ... ```, ``` ... ```, with optional language tag variations.
fn try_extract_from_code_fences(text: &str) -> Option<String> {
    // Find opening fence: ```html, ```HTML, or just ```
    let fence_start = text.find("```")?;
    let after_fence_start = &text[fence_start + 3..];

    // Skip the language identifier (e.g., "html", "HTML", "htm")
    let content_start = match after_fence_start.find('\n') {
        Some(nl_pos) => fence_start + 3 + nl_pos + 1,
        None => return None, // No newline after fence, malformed
    };

    let content = &text[content_start..];

    // Find closing fence
    let content_end = content.rfind("```").unwrap_or(content.len());
    let extracted = content[..content_end].trim();

    // Verify it looks like HTML
    let lower = extracted.to_ascii_lowercase();
    if lower.starts_with("<!doctype") || lower.starts_with("<html") {
        Some(extracted.to_string())
    } else {
        None
    }
}

/// Try to extract HTML embedded in explanatory text.
/// Searches for <!DOCTYPE or <html anywhere and extracts until </html>.
fn try_extract_embedded_html(text: &str) -> Option<String> {
    let lower = text.to_ascii_lowercase();

    // Try different HTML start markers in priority order
    let markers = ["<!doctype html>", "<!doctype", "<html"];

    for marker in markers {
        if let Some(start_pos) = lower.find(marker) {
            let html_candidate = &text[start_pos..];

            // Try to find </html> end marker
            if let Some(end_rel) = html_candidate.to_ascii_lowercase().rfind("</html>") {
                let extracted = html_candidate[..end_rel + 7].trim();
                // If we have complete HTML (with closing tag), accept it regardless of length
                return Some(extracted.to_string());
            }

            // No </html> found - only accept if it's substantial (might be truncated but usable)
            if html_candidate.len() > 100 {
                let extracted = html_candidate.trim_end_matches("```").trim().to_string();
                if extracted.to_ascii_lowercase().starts_with("<!doctype")
                    || extracted.to_ascii_lowercase().starts_with("<html")
                {
                    return Some(extracted);
                }
            }
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fix_css_font_variables() {
        let html = r#"<style>
            body { font-family: var(--font-body); }
            h1 { font-family: var(--font-heading); }
            code { font-family: var(--font-mono); }
        </style>"#;

        let fixed = fix_css_font_variables(html);
        assert!(!fixed.contains("var(--font-"));
        assert!(fixed.contains("'DM Sans', sans-serif"));
        assert!(fixed.contains("'Space Grotesk', sans-serif"));
        assert!(fixed.contains("'JetBrains Mono', monospace"));
    }

    #[test]
    fn test_fix_css_font_variables_extended_patterns() {
        let html = r#"<style>
            .mono { font-family: var(--mono); }
            .sans { font-family: var(--sans); }
            .serif { font-family: var(--serif); }
            .body { font-family: var(--body); }
            .heading { font-family: var(--heading); }
            .body-font { font-family: var(--body-font); }
            .heading-font { font-family: var(--heading-font); }
            .primary { font-family: var(--font-primary); }
            .secondary { font-family: var(--font-secondary); }
        </style>"#;

        let fixed = fix_css_font_variables(html);
        assert!(!fixed.contains("var(--mono)"));
        assert!(!fixed.contains("var(--sans)"));
        assert!(!fixed.contains("var(--serif)"));
        assert!(!fixed.contains("var(--body)"));
        assert!(!fixed.contains("var(--heading)"));
        assert!(!fixed.contains("var(--body-font)"));
        assert!(!fixed.contains("var(--heading-font)"));
        assert!(!fixed.contains("var(--font-primary)"));
        assert!(!fixed.contains("var(--font-secondary)"));

        // Verify replacements use correct display names
        assert!(fixed.contains("'JetBrains Mono', monospace"));
        assert!(fixed.contains("'DM Sans', sans-serif"));
        assert!(fixed.contains("'Libre Baskerville', serif"));
        assert!(fixed.contains("'Space Grotesk', sans-serif"));
    }

    #[test]
    fn test_ensure_hyperframes_interfaces_missing_both() {
        let html = r#"<!DOCTYPE html>
<html>
<head><title>Test</title></head>
<body>
<div class="clip">Content</div>
</body>
</html>"#;

        let fixed = ensure_hyperframes_interfaces(html, 10.5);
        assert!(fixed.contains("window.__timelines"));
        assert!(fixed.contains("window.__hf"));
        assert!(fixed.contains("window.__hf.duration = 10.50"));
        assert!(fixed.contains("seek"));
    }

    #[test]
    fn test_ensure_hyperframes_interfaces_already_present() {
        let html = r#"<!DOCTYPE html>
<html>
<head><title>Test</title></head>
<body>
<div class="clip">Content</div>
<script>
window.__timelines = window.__timelines || {};
window.__hf = { duration: 10, seek: function() {} };
</script>
</body>
</html>"#;

        let fixed = ensure_hyperframes_interfaces(html, 10.5);
        // Safety-net always forces the correct duration regardless of what LLM set
        assert!(
            fixed.contains("window.__hf.duration = 10.50"),
            "Should always force correct duration, got: {}",
            &fixed[fixed.len().saturating_sub(500)..]
        );
        assert!(
            fixed.contains("if (!window.__timelines['ai-generated'])"),
            "Safety-net should check timeline before creating"
        );
    }

    #[test]
    fn test_extract_html_raw_doctype() {
        let input = "<!DOCTYPE html>\n<html><body>Hello</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
        assert!(result.contains("<body>Hello</body>"));
    }

    #[test]
    fn test_extract_html_with_code_fence() {
        let input = "```html\n<!DOCTYPE html>\n<html><body>Test</body></html>\n```";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
        assert!(result.contains("<body>Test</body>"));
    }

    #[test]
    fn test_extract_html_with_leading_text() {
        let input = "Here is the HTML:\n\n<!DOCTYPE html>\n<html><body>Content</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn test_extract_html_no_html_found() {
        let input = "This is just plain text with no HTML.";
        let result = extract_html(input);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.contains("does not contain valid HTML"));
        assert!(err.contains("Response preview"));
    }

    #[test]
    fn test_extract_html_starts_with_html_tag() {
        let input = "<html><head></head><body>Direct</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<html>"));
    }

    #[test]
    fn test_extract_html_whitespace_trimmed() {
        let input = "  \n\n  <!DOCTYPE html>\n<html><body>Trimmed</body></html>  \n  ";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn test_extract_html_case_insensitive_doctype() {
        // LLM might output lowercase doctype
        let input = "<!doctype HTML>\n<html><body>Lower</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.to_ascii_lowercase().starts_with("<!doctype"));
    }

    #[test]
    fn test_extract_html_with_explanatory_prefix() {
        let input = "好的，我来为您生成这个作品。以下是 HTML 代码：\n\n<!DOCTYPE html>\n<html><head><meta charset=\"UTF-8\"></head><body>Content</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
        assert!(result.contains("</html>"));
    }

    #[test]
    fn test_extract_html_code_fence_uppercase() {
        let input = "```HTML\n<!DOCTYPE html>\n<html><body>Upper fence</body></html>\n```";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn test_extract_html_truncated_no_closing_tag() {
        // LLM output truncated, no </html>
        let input = "<!DOCTYPE html>\n<html><head><title>Test</title></head><body><div>Long content that gets cut off...";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }

    // ── ensure_root_duration tests ──────────────────────────────────────────

    #[test]
    fn test_ensure_root_duration_adds_missing() {
        let html = r#"<html data-composition-id="test" data-width="1920">
            <body><div class="clip" data-start="0" data-duration="3">Hi</div></body>
        </html>"#;
        let result = ensure_root_duration(html, 8.5);
        assert!(
            result.contains("data-duration=\"8.500\""),
            "Got: {}",
            result
        );
    }

    #[test]
    fn test_ensure_root_duration_updates_wrong_value() {
        let html = r#"<html data-composition-id="test" data-duration="100" data-width="1920">
            <body><div class="clip" data-start="0" data-duration="3">Hi</div></body>
        </html>"#;
        let result = ensure_root_duration(html, 8.5);
        assert!(
            result.contains("data-duration=\"8.500\""),
            "Got: {}",
            result
        );
        // Should not contain the old wrong value on the composition element
        assert!(
            !result.contains("data-duration=\"100\""),
            "Should have replaced 100, got: {}",
            result
        );
    }

    #[test]
    fn test_ensure_root_duration_preserves_correct_value() {
        let html = r#"<html data-composition-id="test" data-duration="8.5" data-width="1920">
            <body><div class="clip" data-start="0" data-duration="3">Hi</div></body>
        </html>"#;
        let result = ensure_root_duration(html, 8.5);
        // Should still have the correct value (within 0.1 tolerance, so 8.5 is fine)
        assert!(result.contains("data-duration=\"8.5\""), "Got: {}", result);
    }

    #[test]
    fn test_ensure_root_duration_no_composition_id() {
        // No data-composition-id → should not crash, return unchanged
        let html = r#"<html data-width="1920"><body>No composition id</body></html>"#;
        let result = ensure_root_duration(html, 8.5);
        assert_eq!(result, html);
    }

    #[test]
    fn test_ensure_root_duration_single_quotes() {
        let html = r#"<html data-composition-id='test' data-duration='100'>
            <body>Content</body>
        </html>"#;
        let result = ensure_root_duration(html, 8.5);
        assert!(
            result.contains("data-duration=\"8.500\""),
            "Got: {}",
            result
        );
    }

    #[test]
    fn test_ensure_root_duration_ignores_css_selector() {
        // data-composition-id appears first in CSS, then as a real attribute.
        // The fix must target the real element, not the CSS selector.
        let html = r#"<!DOCTYPE html><html>
<head><style>[data-composition-id="ai-generated"] { background: black; }</style></head>
<body>
<div data-composition-id="ai-generated" data-width="1920" data-height="1080" data-duration="480">
<div class="clip" data-start="0" data-duration="3">Hi</div>
</div>
</body></html>"#;
        let result = ensure_root_duration(html, 116.273);
        // The real element's data-duration should be corrected
        assert!(
            result.contains("data-duration=\"116.273\""),
            "Got: {}",
            result
        );
        // The wrong 480 value must be gone
        assert!(
            !result.contains("data-duration=\"480\""),
            "Should have replaced 480, got: {}",
            result
        );
        // The CSS selector must remain untouched
        assert!(
            result.contains("[data-composition-id=\"ai-generated\"]"),
            "CSS selector should be intact"
        );
    }

    #[test]
    fn test_clamp_overflow_clips() {
        let html = r#"<html><body>
<div class="clip" data-start="0" data-duration="50">A</div>
<div class="clip" data-start="50" data-duration="200">B overflows</div>
</body></html>"#;
        // total duration = 100s; clip B (start 50 + dur 200 = 250) must clamp to dur=50
        let result = clamp_overflow_clips(html, 100.0);
        assert!(
            result.contains("data-duration=\"50.000\""),
            "Got: {}",
            result
        );
        // clip A is within bounds, untouched
        assert!(
            result.contains("data-start=\"0\" data-duration=\"50\""),
            "Got: {}",
            result
        );
    }
}
