//! Agentic Hyperframes composition generation using rig.
//!
//! This module implements a local AI agent that uses the official Hyperframes
//! skill files (`.agents/skills/hyperframes/`) as dynamic context, with tools
//! for validation, reference loading, and iterative self-correction.
//!
//! Architecture:
//! - System prompt: loaded from SKILL.md (core rules, always present)
//! - Tools:
//!   - `read_reference`: load skill reference docs on demand
//!   - `validate_html`: run composition validation
//! - Agent loop: plan → generate → validate → fix (multi-turn)

use log::info;
use rig_core::client::CompletionClient;
use rig_core::completion::Prompt;
use rig_core::providers;
use serde::{Deserialize, Serialize};
use serde_json::json;

use super::timeline::TimelineEntry;
use super::validation::validate_composition;

// Auto-generated by build.rs: embeds all `.agents/skills/hyperframes/` files at compile time.
// This removes the runtime dependency on the filesystem, which is unavailable in production
// builds (CWD is `/` on macOS/Linux app bundles).
mod skills_embedded {
    include!(concat!(env!("OUT_DIR"), "/skills_embedded.rs"));
}

// ─── Skills Loader (compile-time embedded) ───────────────────────────────────

/// Manages skill files embedded at compile time from `.agents/skills/hyperframes/`.
/// All content lives in the binary — no runtime filesystem access needed.
pub struct SkillsContext {
    /// Cached system prompt (SKILL.md + house-style + motion-principles)
    pub system_prompt: String,
}

/// Look up an embedded skill file by its path relative to the skills directory.
fn get_embedded_file(rel_path: &str) -> Option<&'static str> {
    skills_embedded::FILES
        .iter()
        .find(|(p, _)| *p == rel_path)
        .map(|(_, c)| *c)
}

impl SkillsContext {
    /// Create a new SkillsContext by composing the system prompt from embedded files.
    pub fn new() -> Result<Self, String> {
        let skill_md = get_embedded_file("SKILL.md")
            .ok_or_else(|| "SKILL.md not found in embedded skills".to_string())?;
        let house_style = get_embedded_file("house-style.md").unwrap_or_default();
        let motion_principles =
            get_embedded_file("references/motion-principles.md").unwrap_or_default();

        // Keep system prompt lean (~45K chars) — beat-direction and techniques
        // are available on-demand via read_reference tool to save tokens.
        let system_prompt = format!(
            "{}\n\n---\n\n# House Style (always loaded)\n\n{}\n\n---\n\n# Motion Principles (always loaded)\n\n{}",
            skill_md, house_style, motion_principles
        );

        Ok(Self { system_prompt })
    }
}

// ─── Agent Builder ──────────────────────────────────────────────────────────

/// Configuration for the agent-based generation.
pub struct AgentConfig {
    pub api_endpoint: String,
    pub api_key: String,
    pub model: String,
}

/// Run the agent-based Hyperframes generation pipeline.
///
/// This is the main entry point for the agent mode. It:
/// 1. Loads skills context (SKILL.md + house-style + motion-principles)
/// 2. Builds a rig agent with tools (read_reference, validate_html)
/// 3. Sends the timeline data as a user prompt
/// 4. Lets the agent iterate (generate → validate → fix) via multi-turn
/// 5. Extracts the final HTML from the agent's response
pub async fn generate_with_agent(
    entries: &[TimelineEntry],
    config: &AgentConfig,
    on_progress: Option<Box<dyn Fn(&str) + Send + Sync>>,
    user_instructions: Option<&str>,
) -> Result<String, String> {
    let report = |msg: &str| {
        if let Some(ref cb) = on_progress {
            cb(msg);
        }
    };

    report("loading_skills");

    // Load skills context
    let skills = SkillsContext::new()?;
    info!(
        "[Agent] Skills loaded (system prompt: {} chars)",
        skills.system_prompt.len(),
    );

    report("building_agent");

    // Build the OpenAI-compatible client (CompletionsClient for /chat/completions API)
    let client = providers::openai::CompletionsClient::builder()
        .api_key(&config.api_key)
        .base_url(&config.api_endpoint)
        .build()
        .map_err(|e| format!("Failed to build LLM client: {}", e))?;

    // Build the agent — no tools needed for single-turn generation.
    // All references are embedded in the system prompt.
    let agent = client
        .agent(&config.model)
        .preamble(&skills.system_prompt)
        .temperature(0.9)
        // Disable thinking mode for Qwen3 models — it adds 2-5 minutes per turn
        // and is unnecessary for code generation tasks.
        .additional_params(json!({ "enable_thinking": false }))
        .build();

    // Build the user prompt with timeline data
    let total_duration: f64 = entries
        .iter()
        .map(|e| e.start_time + e.duration)
        .fold(0.0_f64, f64::max);

    let timeline_json = build_timeline_prompt(entries, total_duration);

    let user_prompt = format!(
        r#"请为以下有声书时间轴创作一个完整的 Hyperframes 视觉作品。

直接生成完整的 HTML composition（从 <!DOCTYPE html> 到 </html>），不要用代码块包裹。
{user_section}
时间轴数据：
{timeline}

总时长：{duration:.1} 秒
条目数：{count}

关键约束（必须遵守）：
1. composition-id 使用 "ai-generated"
2. 尺寸 1920x1080，FPS 30
3. 所有动画使用 GSAP，挂在 paused timeline 上
4. 不要用 Math.random()、Date.now()、repeat: -1
5. **必须实现 window.__hf 接口**（hyperframes 0.6.x 要求）：
   ```javascript
   window.__hf = {{
     duration: {duration:.2},
     seek: function(time) {{
       if (window.__timelines) {{
         Object.values(window.__timelines).forEach(tl => tl.seek(time));
       }}
     }}
   }};
   ```
6. 注册 timeline: `window.__timelines["ai-generated"] = gsap.timeline({{ paused: true }});`
7. 确保 window.__hf 在页面加载时同步创建（不要在 async/await 或 setTimeout 中）"#,
        user_section = match user_instructions {
            Some(instructions) if !instructions.is_empty() =>
                format!("\n用户额外要求（请务必遵循）：\n{}\n", instructions),
            _ => String::new(),
        },
        timeline = timeline_json,
        duration = total_duration,
        count = entries.len(),
    );

    report("agent_generating");

    // Run the agent with single turn — force direct HTML generation.
    // All necessary references (beat-direction, techniques) are already in the system prompt.
    // Tool calls would waste turns on read_reference instead of generating.
    let start = std::time::Instant::now();
    info!("[Agent] Sending prompt to LLM (model: {})...", config.model);
    let response = agent
        .prompt(&user_prompt)
        .max_turns(1)
        .await
        .map_err(|e| format!("Agent execution failed: {}", e))?;
    info!("[Agent] LLM response received in {:?}", start.elapsed());

    report("extracting_html");

    // Log the response for debugging — use char boundary safe truncation
    info!("[Agent] Response length: {} chars", response.len());
    let preview_end = response
        .char_indices()
        .take_while(|(i, _)| *i < 200)
        .last()
        .map(|(i, c)| i + c.len_utf8())
        .unwrap_or(0);
    info!("[Agent] Response preview: {}", &response[..preview_end]);

    // Extract HTML from the agent's final response
    let html = extract_html(&response)?;

    // Final validation
    match validate_composition(&html) {
        Ok(()) => {
            info!("[Agent] Generation complete, validation passed");
            report("agent_done");
            Ok(html)
        }
        Err(errors) => {
            info!(
                "[Agent] Generation complete with {} validation warnings",
                errors.len()
            );
            report("agent_done_with_warnings");
            Ok(html)
        }
    }
}

/// Build the timeline data as a JSON string for the user prompt.
fn build_timeline_prompt(entries: &[TimelineEntry], total_duration: f64) -> String {
    #[derive(Serialize)]
    struct TimelineData {
        total_duration: f64,
        entries: Vec<EntryData>,
    }

    #[derive(Serialize)]
    struct EntryData {
        text: String,
        start: f64,
        duration: f64,
        character: String,
        section: String,
    }

    let data = TimelineData {
        total_duration,
        entries: entries
            .iter()
            .map(|e| EntryData {
                text: e.text.clone(),
                start: e.start_time,
                duration: e.duration,
                character: e.character_name.clone().unwrap_or_default(),
                section: e.section_title.clone().unwrap_or_default(),
            })
            .collect(),
    };

    serde_json::to_string_pretty(&data).unwrap_or_default()
}

/// Extract the HTML content from the LLM response.
///
/// The LLM is instructed to output raw HTML without code fences, but sometimes
/// it wraps the output in ```html ... ``` blocks. This function handles both cases.
fn extract_html(response: &str) -> Result<String, String> {
    let trimmed = response.trim();

    // If it starts with <!DOCTYPE or <html, it's already raw HTML
    if trimmed.starts_with("<!DOCTYPE")
        || trimmed.starts_with("<html")
        || trimmed.starts_with("<!doctype")
    {
        return Ok(trimmed.to_string());
    }

    // Try to strip markdown code fences
    if trimmed.starts_with("```") {
        // Find the end of the opening fence line
        if let Some(first_newline) = trimmed.find('\n') {
            let after_fence = &trimmed[first_newline + 1..];
            let content = after_fence
                .strip_suffix("```")
                .unwrap_or(after_fence)
                .trim();
            if content.starts_with("<!DOCTYPE")
                || content.starts_with("<html")
                || content.starts_with("<!doctype")
            {
                return Ok(content.to_string());
            }
        }
    }

    // Last resort: look for <!DOCTYPE or <html anywhere in the text
    if let Some(start) = trimmed.find("<!DOCTYPE") {
        let html_content = &trimmed[start..];
        let end = html_content.rfind("</html>").map(|i| i + 7).unwrap_or(html_content.len());
        return Ok(html_content[..end].trim_end_matches("```").trim().to_string());
    }
    if let Some(start) = trimmed.find("<!doctype") {
        let html_content = &trimmed[start..];
        let end = html_content.rfind("</html>").map(|i| i + 7).unwrap_or(html_content.len());
        return Ok(html_content[..end].trim_end_matches("```").trim().to_string());
    }
    if let Some(start) = trimmed.find("<html") {
        let html_content = &trimmed[start..];
        let end = html_content.rfind("</html>").map(|i| i + 7).unwrap_or(html_content.len());
        return Ok(html_content[..end].trim_end_matches("```").trim().to_string());
    }

    if let Some(start) = trimmed.find("<!DOCTYPE html>") {
        return Ok(trimmed[start..].trim().to_string());
    }

    Err(format!(
        "LLM response does not contain valid HTML. Response preview: {}",
        &trimmed[..trimmed.len().min(200)]
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_html_raw_doctype() {
        let input = "<!DOCTYPE html>\n<html><body>Hello</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
        assert!(result.contains("<body>Hello</body>"));
    }

    #[test]
    fn test_extract_html_with_code_fence() {
        let input = "```html\n<!DOCTYPE html>\n<html><body>Test</body></html>\n```";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
        assert!(result.contains("<body>Test</body>"));
    }

    #[test]
    fn test_extract_html_with_leading_text() {
        let input = "Here is the HTML:\n\n<!DOCTYPE html>\n<html><body>Content</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn test_extract_html_no_html_found() {
        let input = "This is just plain text with no HTML.";
        let result = extract_html(input);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("does not contain valid HTML"));
    }

    #[test]
    fn test_extract_html_starts_with_html_tag() {
        let input = "<html><head></head><body>Direct</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<html>"));
    }

    #[test]
    fn test_extract_html_whitespace_trimmed() {
        let input = "  \n\n  <!DOCTYPE html>\n<html><body>Trimmed</body></html>  \n  ";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }
}
