//! Agentic Hyperframes composition generation using rig.
//!
//! This module implements a local AI agent that uses the official Hyperframes
//! skill files (`.agents/skills/hyperframes/`) as dynamic context, with tools
//! for validation, reference loading, and iterative self-correction.
//!
//! Architecture:
//! - System prompt: loaded from SKILL.md (core rules, always present)
//! - Tools:
//!   - `read_reference`: load skill reference docs on demand
//!   - `validate_html`: run composition validation
//! - Agent loop: plan → generate → validate → fix (multi-turn)

use log::info;
use rig_core::client::CompletionClient;
use rig_core::completion::Prompt;
use rig_core::providers;
use serde::Serialize;
use serde_json::json;

use super::timeline::TimelineEntry;
use super::validation::validate_composition;

// Auto-generated by build.rs: embeds all `.agents/skills/hyperframes/` files at compile time.
// This removes the runtime dependency on the filesystem, which is unavailable in production
// builds (CWD is `/` on macOS/Linux app bundles).
mod skills_embedded {
    include!(concat!(env!("OUT_DIR"), "/skills_embedded.rs"));
}

// ─── Skills Loader (compile-time embedded) ───────────────────────────────────

/// Manages skill files embedded at compile time from `.agents/skills/hyperframes/`.
/// All content lives in the binary — no runtime filesystem access needed.
pub struct SkillsContext {
    /// Cached system prompt (SKILL.md + house-style + motion-principles)
    pub system_prompt: String,
}

/// Look up an embedded skill file by its path relative to the skills directory.
fn get_embedded_file(rel_path: &str) -> Option<&'static str> {
    skills_embedded::FILES
        .iter()
        .find(|(p, _)| *p == rel_path)
        .map(|(_, c)| *c)
}

impl SkillsContext {
    /// Create a new SkillsContext by composing the system prompt from embedded files.
    pub fn new() -> Result<Self, String> {
        let skill_md = get_embedded_file("SKILL.md")
            .ok_or_else(|| "SKILL.md not found in embedded skills".to_string())?;
        let house_style = get_embedded_file("house-style.md").unwrap_or_default();
        let motion_principles =
            get_embedded_file("references/motion-principles.md").unwrap_or_default();

        // Keep system prompt lean (~45K chars) — beat-direction and techniques
        // are available on-demand via read_reference tool to save tokens.
        let system_prompt = format!(
            "{}\n\n---\n\n# House Style (always loaded)\n\n{}\n\n---\n\n# Motion Principles (always loaded)\n\n{}",
            skill_md, house_style, motion_principles
        );

        Ok(Self { system_prompt })
    }
}

// ─── Agent Builder ──────────────────────────────────────────────────────────

/// Configuration for the agent-based generation.
pub struct AgentConfig {
    pub api_endpoint: String,
    pub api_key: String,
    pub model: String,
}

/// Run the agent-based Hyperframes generation pipeline.
///
/// This is the main entry point for the agent mode. It:
/// 1. Loads skills context (SKILL.md + house-style + motion-principles)
/// 2. Builds a rig agent with tools (read_reference, validate_html)
/// 3. Sends the timeline data as a user prompt
/// 4. Lets the agent iterate (generate → validate → fix) via multi-turn
/// 5. Extracts the final HTML from the agent's response
pub async fn generate_with_agent(
    entries: &[TimelineEntry],
    config: &AgentConfig,
    on_progress: Option<Box<dyn Fn(&str) + Send + Sync>>,
    user_instructions: Option<&str>,
) -> Result<String, String> {
    let report = |msg: &str| {
        if let Some(ref cb) = on_progress {
            cb(msg);
        }
    };

    report("loading_skills");

    // Load skills context
    let skills = SkillsContext::new()?;
    info!(
        "[Agent] Skills loaded (system prompt: {} chars)",
        skills.system_prompt.len(),
    );

    report("building_agent");

    // Build the OpenAI-compatible client (CompletionsClient for /chat/completions API)
    let client = providers::openai::CompletionsClient::builder()
        .api_key(&config.api_key)
        .base_url(&config.api_endpoint)
        .build()
        .map_err(|e| format!("Failed to build LLM client: {}", e))?;

    // Build the agent — no tools needed for single-turn generation.
    // All references are embedded in the system prompt.
    let agent = client
        .agent(&config.model)
        .preamble(&skills.system_prompt)
        // Lower temperature for more deterministic output format compliance.
        // 0.6 balances creativity (for visual design) with format stability.
        .temperature(0.6)
        // Enable thinking mode for better code structure generation.
        // Adds 2-5 minutes but significantly improves compliance with
        // complex requirements like window.__hf interface implementation.
        .additional_params(json!({ "enable_thinking": false }))
        .build();

    // Build the user prompt with timeline data
    let total_duration: f64 = entries
        .iter()
        .map(|e| e.start_time + e.duration)
        .fold(0.0_f64, f64::max);

    let timeline_json = build_timeline_prompt(entries, total_duration);

    let user_prompt = format!(
        r#"为以下有声书时间轴生成 Hyperframes HTML 作品。

时间轴数据：
{timeline}

总时长：{duration:.1} 秒，条目数：{count}
{user_section}

技术要求：
- composition-id="ai-generated"，尺寸 1920x1080
- GSAP 动画，timeline 用 paused: true
- 实现 window.__hf = {{ duration: {duration:.2}, seek: fn(t) {{ Object.values(window.__timelines).forEach(tl => tl.seek(t)) }} }}
- 字体用 inter 或 roboto
- 禁止：Math.random()、Date.now()、repeat:-1

【输出格式 - 严格遵守】
直接输出完整的原始 HTML 文档，以 <!DOCTYPE html> 开头，以 </html> 结尾。
不要输出任何解释文字、分析过程、或代码围栏（```）。
只输出 HTML，不要前后有任何其他内容。"#,
        user_section = match user_instructions {
            Some(instructions) if !instructions.is_empty() =>
                format!("\n用户额外要求（请务必遵循）：\n{}\n", instructions),
            _ => String::new(),
        },
        timeline = timeline_json,
        duration = total_duration,
        count = entries.len(),
    );

    report("agent_generating");

    // Run the agent with single turn — force direct HTML generation.
    // All necessary references (beat-direction, techniques) are already in the system prompt.
    // Tool calls would waste turns on read_reference instead of generating.
    let start = std::time::Instant::now();
    info!("[Agent] Sending prompt to LLM (model: {})...", config.model);
    let response = agent
        .prompt(&user_prompt)
        .max_turns(1)
        .await
        .map_err(|e| format!("Agent execution failed: {}", e))?;
    info!("[Agent] LLM response received in {:?}", start.elapsed());

    report("extracting_html");

    // Log the response for debugging — use char boundary safe truncation
    info!("[Agent] Response length: {} chars", response.len());
    let preview_end = response
        .char_indices()
        .take_while(|(i, _)| *i < 200)
        .last()
        .map(|(i, c)| i + c.len_utf8())
        .unwrap_or(0);
    info!("[Agent] Response preview: {}", &response[..preview_end]);

    // Extract HTML from the agent's final response
    let html = extract_html(&response)?;

    // Post-process: fix common issues as a safety net
    let html = fix_css_font_variables(&html);
    let html = ensure_hyperframes_interfaces(&html, total_duration);

    // Final validation
    match validate_composition(&html) {
        Ok(()) => {
            info!("[Agent] Generation complete, validation passed");
            report("agent_done");
            Ok(html)
        }
        Err(errors) => {
            info!(
                "[Agent] Generation complete with {} validation warnings",
                errors.len()
            );
            report("agent_done_with_warnings");
            Ok(html)
        }
    }
}

/// Build the timeline data as a JSON string for the user prompt.
fn build_timeline_prompt(entries: &[TimelineEntry], total_duration: f64) -> String {
    #[derive(Serialize)]
    struct TimelineData {
        total_duration: f64,
        entries: Vec<EntryData>,
    }

    #[derive(Serialize)]
    struct EntryData {
        text: String,
        start: f64,
        duration: f64,
        character: String,
        section: String,
    }

    let data = TimelineData {
        total_duration,
        entries: entries
            .iter()
            .map(|e| EntryData {
                text: e.text.clone(),
                start: e.start_time,
                duration: e.duration,
                character: e.character_name.clone().unwrap_or_default(),
                section: e.section_title.clone().unwrap_or_default(),
            })
            .collect(),
    };

    serde_json::to_string_pretty(&data).unwrap_or_default()
}

/// Fix CSS font variables by replacing var(--font-*) with actual font names.
/// This is necessary because hyperframes cannot map CSS variables to fonts.
fn fix_css_font_variables(html: &str) -> String {
    let mut result = html.to_string();

    // Replace common font variable patterns with hyperframes-supported fonts
    // Pattern 1: Standard --font-* naming
    result = result
        .replace("var(--font-body)", "'inter', sans-serif")
        .replace("var(--font-heading)", "'montserrat', sans-serif")
        .replace("var(--font-mono)", "'jetbrains-mono', monospace")
        .replace("var(--font-main)", "'inter', sans-serif")
        .replace("var(--font-display)", "'montserrat', sans-serif")
        .replace("var(--font-serif)", "'eb-garamond', serif")
        .replace("var(--font-sans)", "'roboto', sans-serif");

    // Pattern 2: Short naming (--mono, --sans, --serif)
    result = result
        .replace("var(--mono)", "'jetbrains-mono', monospace")
        .replace("var(--sans)", "'roboto', sans-serif")
        .replace("var(--serif)", "'eb-garamond', serif")
        .replace("var(--body)", "'inter', sans-serif")
        .replace("var(--heading)", "'montserrat', sans-serif");

    // Pattern 3: Suffix naming (--body-font, --heading-font)
    result = result
        .replace("var(--body-font)", "'inter', sans-serif")
        .replace("var(--heading-font)", "'montserrat', sans-serif")
        .replace("var(--mono-font)", "'jetbrains-mono', monospace");

    // Pattern 4: Primary/secondary naming
    result = result
        .replace("var(--font-primary)", "'inter', sans-serif")
        .replace("var(--font-secondary)", "'montserrat', sans-serif");

    result
}

/// Ensure required Hyperframes interfaces exist (window.__hf and window.__timelines).
/// This is a safety net to fix LLM omissions and ensure hyperframes render compatibility.
fn ensure_hyperframes_interfaces(html: &str, duration: f64) -> String {
    let mut result = html.to_string();

    // Check if window.__hf exists
    let has_hf = html.contains("window.__hf");

    // Check if window.__timelines exists
    let has_timelines = html.contains("window.__timelines");

    // If both exist, no need to inject
    if has_hf && has_timelines {
        return result;
    }

    // Build injection script
    let mut script = String::from("<script>\n");

    if !has_timelines {
        script.push_str("  // Initialize window.__timelines if missing\n");
        script.push_str("  window.__timelines = window.__timelines || {};\n");
        script.push_str("  window.__timelines['ai-generated'] = gsap.timeline({ paused: true });\n");
    }

    if !has_hf {
        script.push_str("  // Initialize window.__hf if missing\n");
        script.push_str("  window.__hf = {\n");
        script.push_str(&format!("    duration: {:.2},\n", duration));
        script.push_str("    seek: function(time) {\n");
        script.push_str("      if (window.__timelines) {\n");
        script.push_str("        Object.values(window.__timelines).forEach(function(tl) {\n");
        script.push_str("          tl.seek(time);\n");
        script.push_str("        });\n");
        script.push_str("      }\n");
        script.push_str("    }\n");
        script.push_str("  };\n");
    }

    script.push_str("</script>");

    // Inject before </body> if it exists, otherwise append
    if let Some(pos) = result.rfind("</body>") {
        result.insert_str(pos, &script);
    } else {
        result.push_str(&script);
    }

    info!(
        "[Agent] Post-processed: injected missing interfaces (has_hf={}, has_timelines={})",
        has_hf, has_timelines
    );

    result
}

/// Extract the HTML content from the LLM response.
///
/// The LLM is instructed to output raw HTML, but may still wrap it in
/// explanations or code fences. This function handles multiple cases:
/// 1. Raw HTML (starts with <!DOCTYPE or <html)
/// 2. HTML wrapped in ```html ... ``` code fences
/// 3. HTML embedded in explanatory text
/// 4. HTML with leading/trailing whitespace or text
fn extract_html(response: &str) -> Result<String, String> {
    let trimmed = response.trim();

    // Fast path: already raw HTML
    if let Some(html) = try_extract_raw_html(trimmed) {
        return Ok(html);
    }

    // Try to strip markdown code fences: ```html ... ``` or ``` ... ```
    if let Some(html) = try_extract_from_code_fences(trimmed) {
        return Ok(html);
    }

    // Last resort: search for HTML patterns anywhere in the text
    if let Some(html) = try_extract_embedded_html(trimmed) {
        return Ok(html);
    }

    // Generate a better error message with actual preview
    let preview: String = trimmed.chars().take(300).collect();
    Err(format!(
        "LLM response does not contain valid HTML.\n\nResponse preview (first 300 chars):\n{}\n\n\
         Hint: Ensure the model outputs raw HTML starting with <!DOCTYPE html> or <html>.",
        preview
    ))
}

/// Try to extract HTML that starts at the beginning of the text.
fn try_extract_raw_html(text: &str) -> Option<String> {
    let lower = text.to_ascii_lowercase();
    if lower.starts_with("<!doctype") || lower.starts_with("<html") {
        Some(text.trim().to_string())
    } else {
        None
    }
}

/// Try to extract HTML from markdown code fences.
/// Handles: ```html ... ```, ``` ... ```, with optional language tag variations.
fn try_extract_from_code_fences(text: &str) -> Option<String> {
    // Find opening fence: ```html, ```HTML, or just ```
    let fence_start = text.find("```")?;
    let after_fence_start = &text[fence_start + 3..];

    // Skip the language identifier (e.g., "html", "HTML", "htm")
    let content_start = match after_fence_start.find('\n') {
        Some(nl_pos) => fence_start + 3 + nl_pos + 1,
        None => return None, // No newline after fence, malformed
    };

    let content = &text[content_start..];

    // Find closing fence
    let content_end = content.rfind("```").unwrap_or(content.len());
    let extracted = content[..content_end].trim();

    // Verify it looks like HTML
    let lower = extracted.to_ascii_lowercase();
    if lower.starts_with("<!doctype") || lower.starts_with("<html") {
        Some(extracted.to_string())
    } else {
        None
    }
}

/// Try to extract HTML embedded in explanatory text.
/// Searches for <!DOCTYPE or <html anywhere and extracts until </html>.
fn try_extract_embedded_html(text: &str) -> Option<String> {
    let lower = text.to_ascii_lowercase();

    // Try different HTML start markers in priority order
    let markers = ["<!doctype html>", "<!doctype", "<html"];

    for marker in markers {
        if let Some(start_pos) = lower.find(marker) {
            let html_candidate = &text[start_pos..];

            // Try to find </html> end marker
            if let Some(end_rel) = html_candidate.to_ascii_lowercase().rfind("</html>") {
                let extracted = html_candidate[..end_rel + 7].trim();
                // If we have complete HTML (with closing tag), accept it regardless of length
                return Some(extracted.to_string());
            }

            // No </html> found - only accept if it's substantial (might be truncated but usable)
            if html_candidate.len() > 100 {
                let extracted = html_candidate
                    .trim_end_matches("```")
                    .trim()
                    .to_string();
                if extracted.to_ascii_lowercase().starts_with("<!doctype")
                    || extracted.to_ascii_lowercase().starts_with("<html")
                {
                    return Some(extracted);
                }
            }
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fix_css_font_variables() {
        let html = r#"<style>
            body { font-family: var(--font-body); }
            h1 { font-family: var(--font-heading); }
            code { font-family: var(--font-mono); }
        </style>"#;

        let fixed = fix_css_font_variables(html);
        assert!(!fixed.contains("var(--font-"));
        assert!(fixed.contains("'inter', sans-serif"));
        assert!(fixed.contains("'montserrat', sans-serif"));
        assert!(fixed.contains("'jetbrains-mono', monospace"));
    }

    #[test]
    fn test_fix_css_font_variables_extended_patterns() {
        let html = r#"<style>
            .mono { font-family: var(--mono); }
            .sans { font-family: var(--sans); }
            .serif { font-family: var(--serif); }
            .body { font-family: var(--body); }
            .heading { font-family: var(--heading); }
            .body-font { font-family: var(--body-font); }
            .heading-font { font-family: var(--heading-font); }
            .primary { font-family: var(--font-primary); }
            .secondary { font-family: var(--font-secondary); }
        </style>"#;

        let fixed = fix_css_font_variables(html);
        assert!(!fixed.contains("var(--mono)"));
        assert!(!fixed.contains("var(--sans)"));
        assert!(!fixed.contains("var(--serif)"));
        assert!(!fixed.contains("var(--body)"));
        assert!(!fixed.contains("var(--heading)"));
        assert!(!fixed.contains("var(--body-font)"));
        assert!(!fixed.contains("var(--heading-font)"));
        assert!(!fixed.contains("var(--font-primary)"));
        assert!(!fixed.contains("var(--font-secondary)"));

        // Verify replacements
        assert!(fixed.contains("'jetbrains-mono', monospace"));
        assert!(fixed.contains("'roboto', sans-serif"));
        assert!(fixed.contains("'eb-garamond', serif"));
        assert!(fixed.contains("'inter', sans-serif"));
        assert!(fixed.contains("'montserrat', sans-serif"));
    }

    #[test]
    fn test_ensure_hyperframes_interfaces_missing_both() {
        let html = r#"<!DOCTYPE html>
<html>
<head><title>Test</title></head>
<body>
<div class="clip">Content</div>
</body>
</html>"#;

        let fixed = ensure_hyperframes_interfaces(html, 10.5);
        assert!(fixed.contains("window.__timelines"));
        assert!(fixed.contains("window.__hf"));
        assert!(fixed.contains("duration: 10.50"));
        assert!(fixed.contains("seek: function"));
    }

    #[test]
    fn test_ensure_hyperframes_interfaces_already_present() {
        let html = r#"<!DOCTYPE html>
<html>
<head><title>Test</title></head>
<body>
<div class="clip">Content</div>
<script>
window.__timelines = window.__timelines || {};
window.__hf = { duration: 10, seek: function() {} };
</script>
</body>
</html>"#;

        let fixed = ensure_hyperframes_interfaces(html, 10.5);
        // Should not inject if both already exist
        let hf_count = fixed.matches("window.__hf").count();
        assert_eq!(hf_count, 1, "Should not duplicate window.__hf");
    }

    #[test]
    fn test_extract_html_raw_doctype() {
        let input = "<!DOCTYPE html>\n<html><body>Hello</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
        assert!(result.contains("<body>Hello</body>"));
    }

    #[test]
    fn test_extract_html_with_code_fence() {
        let input = "```html\n<!DOCTYPE html>\n<html><body>Test</body></html>\n```";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
        assert!(result.contains("<body>Test</body>"));
    }

    #[test]
    fn test_extract_html_with_leading_text() {
        let input = "Here is the HTML:\n\n<!DOCTYPE html>\n<html><body>Content</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn test_extract_html_no_html_found() {
        let input = "This is just plain text with no HTML.";
        let result = extract_html(input);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.contains("does not contain valid HTML"));
        assert!(err.contains("Response preview"));
    }

    #[test]
    fn test_extract_html_starts_with_html_tag() {
        let input = "<html><head></head><body>Direct</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<html>"));
    }

    #[test]
    fn test_extract_html_whitespace_trimmed() {
        let input = "  \n\n  <!DOCTYPE html>\n<html><body>Trimmed</body></html>  \n  ";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn test_extract_html_case_insensitive_doctype() {
        // LLM might output lowercase doctype
        let input = "<!doctype HTML>\n<html><body>Lower</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.to_ascii_lowercase().starts_with("<!doctype"));
    }

    #[test]
    fn test_extract_html_with_explanatory_prefix() {
        let input = "好的，我来为您生成这个作品。以下是 HTML 代码：\n\n<!DOCTYPE html>\n<html><head><meta charset=\"UTF-8\"></head><body>Content</body></html>";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
        assert!(result.contains("</html>"));
    }

    #[test]
    fn test_extract_html_code_fence_uppercase() {
        let input = "```HTML\n<!DOCTYPE html>\n<html><body>Upper fence</body></html>\n```";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn test_extract_html_truncated_no_closing_tag() {
        // LLM output truncated, no </html>
        let input = "<!DOCTYPE html>\n<html><head><title>Test</title></head><body><div>Long content that gets cut off...";
        let result = extract_html(input).unwrap();
        assert!(result.starts_with("<!DOCTYPE html>"));
    }
}
