//! Prompt building for Hyperframes HTML generation.
//!
//! Builds both the system prompt (from embedded skill files) and
//! the user prompt (with timeline data and visual direction).

// Auto-generated by build.rs: embeds all `.agents/skills/hyperframes/` files at compile time.
// This removes the runtime dependency on the filesystem, which is unavailable in production
// builds (CWD is `/` on macOS/Linux app bundles).
mod skills_embedded {
    include!(concat!(env!("OUT_DIR"), "/skills_embedded.rs"));
}

use serde::Serialize;

use super::timeline::TimelineEntry;

// ─── Skills Loader (compile-time embedded) ───────────────────────────────────

/// Manages skill files embedded at compile time from `.agents/skills/hyperframes/`.
/// All content lives in the binary — no runtime filesystem access needed.
pub struct SkillsContext {
    /// Cached system prompt (SKILL.md + house-style + motion-principles + references)
    pub system_prompt: String,
}

fn get_embedded_file(rel_path: &str) -> Option<&'static str> {
    skills_embedded::FILES
        .iter()
        .find(|(p, _)| *p == rel_path)
        .map(|(_, c)| *c)
}

impl SkillsContext {
    /// Create a new SkillsContext by composing the system prompt from embedded files.
    ///
    /// Loads ALL critical reference documents marked "Always read" in SKILL.md.
    /// Total prompt size ~75K chars — well within modern LLM context limits and
    /// essential for high-quality video composition generation.
    pub fn new() -> Result<Self, String> {
        let skill_md = get_embedded_file("SKILL.md")
            .ok_or_else(|| "SKILL.md not found in embedded skills".to_string())?;
        let house_style = get_embedded_file("house-style.md").unwrap_or_default();
        let motion_principles =
            get_embedded_file("references/motion-principles.md").unwrap_or_default();
        let video_composition =
            get_embedded_file("references/video-composition.md").unwrap_or_default();
        let beat_direction = get_embedded_file("references/beat-direction.md").unwrap_or_default();
        let typography = get_embedded_file("references/typography.md").unwrap_or_default();
        let techniques = get_embedded_file("references/techniques.md").unwrap_or_default();

        let system_prompt = format!(
            "{skill}\n\n---\n\n\
             # House Style (always loaded)\n\n{house}\n\n---\n\n\
             # Motion Principles (always loaded)\n\n{motion}\n\n---\n\n\
             # Video Composition Rules (always loaded)\n\n{video}\n\n---\n\n\
             # Beat Direction (always loaded)\n\n{beat}\n\n---\n\n\
             # Typography (always loaded)\n\n{typo}\n\n---\n\n\
             # Visual Techniques (always loaded)\n\n{tech}",
            skill = skill_md,
            house = house_style,
            motion = motion_principles,
            video = video_composition,
            beat = beat_direction,
            typo = typography,
            tech = techniques,
        );

        Ok(Self { system_prompt })
    }
}

// ─── User Prompt Builder ─────────────────────────────────────────────────────

/// Build the user prompt with timeline data and visual direction.
///
/// `actual_duration_secs` overrides the timeline-computed duration when provided.
/// This should be the ffprobe-measured duration of the merged audio file, ensuring
/// the HTML composition's total duration exactly matches the audio.
pub fn build_user_prompt(
    entries: &[TimelineEntry],
    total_duration: f64,
    user_instructions: Option<&str>,
) -> String {
    let timeline_json = build_timeline_prompt(entries, total_duration);

    format!(
        r#"为以下有声书生成 Hyperframes HTML 视觉伴奏视频。

# 你的角色

你是一位动态影像设计师。音频已有完整旁白，你的视频是"视觉伴奏"——营造氛围、传递情绪、强化记忆点。观众听着音频，看着你的画面感受内容的力量。

# 内容呈现

画面用视觉语言诠释内容的情绪内核——观众在听音频，你的画面负责"看见"文字背后的东西。

为每个场景找到 1-2 个**视觉锚点**——画面中观众视线最先落下的焦点。锚点的形式由内容决定：

- **文字锚**：从内容中提炼的一个短词或短语（≤ 10 字）——金句的灵魂、概念的内核、人名的重量。它是画面里的一枚视觉印章，精炼、有力、一眼入画。
- **符号锚**：一个承载意义的字符或 icon——♛ 代表权力、☠ 代表危机、⚖ 代表抉择。比文字更直觉，跨语言也能感受。
- **隐喻锚**：用一个视觉意象暗示内容——"王朝覆灭"可以是崩塌的柱廊、"暗流涌动"可以是水下的漩涡。这是最有发挥空间的一层。
- **数据锚**：数字、计数器、进度——"一百零八将"用一个跳动的 108 比写五个字更有力。

锚点之间可以自由组合（隐喻背景 + 文字前景）。纯视觉隐喻能传达的场景，画面本身就在说话。

# 视觉丰富度

每个场景 6-10 个视觉元素，分层构建：
- **焦点层**：视觉锚点（文字 80px+ 大字号 / 符号 / 隐喻主体），动感入场（slam / slide / scale / draw）
- **几何层**：旋转圆环、脉动多边形、流动线条网格
- **背景层**：渐变流动、radial glow 呼吸、粒子漂浮
- **结构层**：动态 accent lines、扩展边框、reveal 效果
- **数据层**（可选）：progress bar、counter 计数、node 连接线

让画面持续运动——装饰元素 2-5s 一个循环，主元素入场 0.5-1.2s，元素分批 stagger 入场形成节奏。
"看一眼就能感受到生命力"是你的最低标准。

# 场景与节奏

- 每 10-20 秒一个场景，根据内容和情绪变化划分
- 每个场景有独特的视觉个性（不同主体几何、不同动画方向），但调色板统一
- 场景间用 crossfade / wipe / blur-through 平滑过渡
- 最后一个场景淡出收束，其余场景只做入场动画（退场由过渡处理）
- 参考 beat-direction.md 规划快拍与慢拍交替
- 同一场景内至少 3 种不同的 ease

时间轴数据（JSON）：
{timeline}

总时长：{duration:.2} 秒，条目数：{count}
{user_section}

# 视觉设计

按照 house-style.md 和 video-composition.md 的规则：
1. 选择匹配内容情绪的调色板，声明 bg/fg/accent
2. 选择有特色的字体（参考 typography.md）
3. 场景主视觉运用 techniques.md 中的技巧（SVG drawing、CSS 3D、kinetic type 等）

# 时间轴同步

每个条目的 start 和 duration 精确对应音频时间：
- clip 的 data-start = 条目 start（秒）
- clip 的 data-duration = 条目 duration（秒）
- 条目间的间隔保留
- 整个作品 t=0 开始，t={duration:.2}s 结束
- 多个条目可共享一个视觉场景，但每条仍需对应的 clip 元素

# 渲染引擎技术要求

这些是 Hyperframes 渲染器的硬性要求，违反任何一条都会导致渲染失败：

1. 根元素：data-composition-id="ai-generated"，data-width="1920"，data-height="1080"，data-duration="{duration:.2}"
2. GSAP timeline 使用 paused: true
3. 同步注册 window.__timelines['ai-generated'] = tl;（在 </body> 前的 <script> 中直接执行）
4. 注册方式必须是同步代码——setTimeout、async、Promise 回调中的注册会被渲染器忽略
5. 实现 window.__hf = {{ duration: {duration:.2}, seek: function(t) {{ Object.values(window.__timelines).forEach(function(tl) {{ tl.seek(t) }}) }} }}
6. GSAP CDN: <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
7. 渲染器逐帧截图，所以所有动画必须是确定性的——使用 seed、公式、固定时间线，确保同一帧每次渲染结果完全一致
8. 关键词字号 80px+，数字用 font-variant-numeric: tabular-nums
9. gsap.from() 做入场动画，gsap.to() 仅用于最后场景的退出动画
10. 每个入场 tween 起始时间偏移 0.1-0.3s

# 输出

输出完整 HTML 文档：<!DOCTYPE html> 开头，</html> 结尾，中间不加任何解释文字或代码围栏。"#,
        user_section = match user_instructions {
            Some(instructions) if !instructions.is_empty() =>
                format!("\n用户额外要求（请务必遵循）：\n{instructions}\n"),
            _ => String::new(),
        },
        timeline = timeline_json,
        duration = total_duration,
        count = entries.len(),
    )
}

/// Build the timeline data as a JSON string for the user prompt.
///
/// For audiobook visual accompaniment, we truncate long text entries and provide
/// only the first ~60 chars as context hint. The full text is NOT meant to be
/// displayed verbatim in the video — it's only provided so the LLM can understand
/// the content theme and mood for visual design.
fn build_timeline_prompt(entries: &[TimelineEntry], total_duration: f64) -> String {
    #[derive(Serialize)]
    struct TimelineData {
        total_duration: f64,
        entries: Vec<EntryData>,
    }

    #[derive(Serialize)]
    struct EntryData {
        /// Truncated text hint — for understanding content theme only, NOT for display
        content_hint: String,
        start: f64,
        duration: f64,
        character: String,
        section: String,
    }

    let data = TimelineData {
        total_duration,
        entries: entries
            .iter()
            .map(|e| {
                let hint = if e.text.chars().count() > 60 {
                    let truncated: String = e.text.chars().take(57).collect();
                    format!("{truncated}...")
                } else {
                    e.text.clone()
                };
                EntryData {
                    content_hint: hint,
                    start: e.start_time,
                    duration: e.duration,
                    character: e.character_name.clone().unwrap_or_default(),
                    section: e.section_title.clone().unwrap_or_default(),
                }
            })
            .collect(),
    };

    serde_json::to_string_pretty(&data).unwrap_or_default()
}
